/**
 * Unified Quiz Hub — subject registry
 * task = “bài/đề” (generalized from PRM exam filter)
 */
window.QUIZ_SUBJECTS = {
  prm: {
    id: "prm",
    title: "PRM393",
    subtitle: "Flutter · SP26 · Slides",
    brandIcon: "fa-mobile-screen-button",
    storageWrong: "uq-prm-wrong-v1",
    storageProgress: "uq-prm-progress-v1",
    cloudSubject: "prm",
    multiSelect: true,
    showTranslationAlways: true,
    // Chỉ hiện tab khi có câu (app ẩn count=0)
    tasks: [
      { id: "fe", label: "SP26 FE", icon: "fa-file" },
      { id: "re", label: "SP26 B5 FE", icon: "fa-file-circle-plus" },
      { id: "fuexam", label: "Đề FE", icon: "fa-file-circle-check" },
      { id: "slides", label: "Slides", icon: "fa-chalkboard" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "prm",
    hint: "Chọn đề SP26 / Slides (tab 0 câu sẽ ẩn). Giải thích song ngữ EN–VI.",
  },
  mln: {
    id: "mln",
    title: "MLN",
    subtitle: "Bank 526 · Đề FE",
    brandIcon: "fa-book-open",
    storageWrong: "uq-mln-wrong-v1",
    storageProgress: "uq-mln-progress-v1",
    cloudSubject: "mln",
    multiSelect: true,
    showTranslationAlways: false,
    hideTranslation: true,
    tasks: [
      { id: "bank", label: "Bank 526", icon: "fa-book" },
      { id: "fuexam", label: "Đề FE (bổ sung)", icon: "fa-file-circle-plus" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "mln",
    hint: "Bank MLN + bộ Đề FE bổ sung từ remote. Multi-select khi đáp án nhiều chữ.",
  },
  jit: {
    id: "jit",
    title: "JIT401",
    subtitle: "Quiz · Sample · PT · Slides · Site",
    brandIcon: "fa-laptop-code",
    storageWrong: "uq-jit-wrong-v1",
    storageProgress: "uq-jit-progress-v1",
    cloudSubject: "jit",
    multiSelect: false,
    showTranslationAlways: true,
    tasks: [
      { id: "quiz", label: "Quiz", icon: "fa-list-check" },
      { id: "sample", label: "Sample", icon: "fa-flask" },
      { id: "pt", label: "Quiz PT", icon: "fa-pen-to-square" },
      { id: "fuexam", label: "Đề FE", icon: "fa-file-circle-check" },
      { id: "slides", label: "Slides (bổ sung)", icon: "fa-chalkboard" },
      { id: "site", label: "Site (bổ sung)", icon: "fa-globe" },
      { id: "albazzz", label: "Albazzz", icon: "fa-book" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "jit",
    hint: "Quiz / Sample / PT + Slides + Site (MLN122). Tab 0 câu sẽ ẩn. JP + bảng dịch VI.",
  },
  // dataKey vẫn "fe" (file data/fe.js); hiển thị JFE — URL ?s=fe hoặc ?s=jfe
  fe: {
    id: "fe",
    title: "JFE301",
    subtitle: "Test · 300 · Books · Đề FE",
    brandIcon: "fa-graduation-cap",
    storageWrong: "uq-fe-wrong-v1",
    storageProgress: "uq-fe-progress-v1",
    cloudSubject: "fe",
    multiSelect: false,
    showTranslationAlways: true,
    tasks: [
      { id: "test", label: "Test", icon: "fa-vial" },
      { id: "bank300", label: "300 câu", icon: "fa-database" },
      { id: "datajfe", label: "datajfe", icon: "fa-file-image" },
      { id: "albazzz", label: "Albazzz", icon: "fa-book" },
      { id: "books", label: "Books (bổ sung)", icon: "fa-book-open" },
      { id: "fuexam", label: "Đề FE (bổ sung)", icon: "fa-file-circle-plus" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "fe",
    hint: "JFE301: test · 300 · datajfe + Books/Đề FE. Tab 0 câu được ẩn.",
  },
  prn232: {
    id: "prn232",
    title: "PRN232",
    subtitle: "150 MCQ · SP26/B5/FA25 FE · PE thực hành",
    brandIcon: "fa-code",
    storageWrong: "uq-prn232-wrong-v1",
    storageProgress: "uq-prn232-progress-v1",
    cloudSubject: "prn232",
    multiSelect: true,
    showTranslationAlways: true,
    tasks: [
      { id: "fe", label: "SP26 FE", icon: "fa-file-circle-check" },
      { id: "feb5", label: "SP26 B5 FE", icon: "fa-file-circle-plus" },
      { id: "fefa25", label: "FA25 FE", icon: "fa-file" },
      { id: "pe", label: "Đề PE", icon: "fa-laptop-code" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "prn232",
    hint: "PRN232: 50 SP26 FE + 50 B5 FE + 50 FA25 FE. Tab PE trống (đề thực hành VS/.NET 8). OCR có thể lệch — đối chiếu ảnh gốc khi nghi ngờ.",
  },
  ite: {
    id: "ite",
    title: "ITE302c",
    subtitle: "Ethics in IT · 12 Đề FE + 340 Câu Quizlet (1060 MCQ)",
    brandIcon: "fa-scale-balanced",
    storageWrong: "uq-ite-wrong-v1",
    storageProgress: "uq-ite-progress-v1",
    cloudSubject: "ite",
    multiSelect: true,
    showTranslationAlways: true,
    tasks: [
      { id: "c340", label: "340 câu", icon: "fa-book" },
      { id: "sp26_fe_re", label: "SP26 FE RE", icon: "fa-file-circle-check" },
      { id: "sp26_fe", label: "SP26 FE", icon: "fa-file" },
      { id: "su25_fe_re", label: "SU25 FE RE", icon: "fa-file-circle-check" },
      { id: "su25_fe", label: "SU25 FE", icon: "fa-file" },
      { id: "sp25_fe_re", label: "SP25 FE RE", icon: "fa-file-circle-check" },
      { id: "sp25_fe", label: "SP25 FE", icon: "fa-file" },
      { id: "fa24_fe_re", label: "FA24 FE RE", icon: "fa-file-circle-check" },
      { id: "fa24_fe", label: "FA24 FE", icon: "fa-file" },
      { id: "su24_fe_re", label: "SU24 FE RE", icon: "fa-file-circle-check" },
      { id: "su24_fe", label: "SU24 FE", icon: "fa-file" },
      { id: "sp24_fe_re", label: "SP24 FE RE", icon: "fa-file-circle-check" },
      { id: "sp24_fe", label: "SP24 FE", icon: "fa-file" },
      { id: "ite_unique", label: "Đề không trùng", icon: "fa-circle-check" },
      { id: "all", label: "Tất cả", icon: "fa-layer-group" },
    ],
    defaultTask: "all",
    dataKey: "ite",
    hint: "ITE302c (Ethics in IT): 12 đề FE từ FuExam.me + 340 câu Quizlet (tổng cộng 1060 câu).",
  },
};

window.QUIZ_SUBJECT_ORDER = ["prm", "mln", "jit", "fe", "prn232", "ite"];
