# -*- coding: utf-8 -*-
"""Build PRM393 quiz data from SP26 FE exams (B5 + FE)."""
from __future__ import annotations

import json
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent


def Q(
    source: str,
    num: int,
    question: str,
    options: dict[str, str],
    answer: str,
    question_vi: str,
    options_vi: dict[str, str],
    concept: str,
    why_correct: str,
    why_wrong: dict[str, str],
    tip: str,
) -> dict:
    letters = ["A", "B", "C", "D"]
    ans = answer.upper()
    disp = f"{ans}. {options_vi.get(ans) or options.get(ans, '')}"
    why = f"【Khái niệm】{concept}\n\n【Vì sao đúng】{why_correct}"
    # exam code for quiz filter: b5 -> tab "re" (B5), other FE -> "fe"
    exam_code = "re" if "B5" in source else "fe"
    return {
        "source": source,
        "num": num,
        "exam": exam_code,
        "examLabel": source,
        "question": question,
        "options": {k: options[k] for k in letters if k in options},
        "answer": ans,
        "alternatives": [],
        "explanation": {
            "questionVi": question_vi,
            "optionsVi": {k: options_vi[k] for k in letters if k in options_vi},
            "answerDisplay": disp,
            "concept": concept,
            "whyCorrect": why,
            "memoryTip": tip,
            "whyWrong": {k: why_wrong[k] for k in letters if k in why_wrong and k != ans},
        },
    }


# fmt: off
B5: list[dict] = [
Q("SP26-B5-FE", 1,
  "Which widget pattern protects authenticated routes?",
  {"A":"Navigator","B":"Guard","C":"Route protection","D":"Middleware"},
  "B",
  "Mẫu widget nào bảo vệ các route yêu cầu đăng nhập (authenticated routes)?",
  {"A":"Navigator","B":"Guard","C":"Route protection","D":"Middleware"},
  "Route Guard (bảo vệ route) là pattern chặn/cho phép điều hướng dựa trên trạng thái đăng nhập. Khi user chưa login, Guard chuyển hướng sang màn login thay vì mở trang được bảo vệ.",
  "Guard là pattern chuẩn để bảo vệ route đã xác thực: kiểm tra auth trước khi cho vào màn hình. Trong Flutter thường kết hợp GoRouter redirect, AutoRoute guards, hoặc wrapper widget kiểm tra token/session.",
  {"A":"Navigator chỉ điều hướng giữa các màn, không tự bảo vệ auth.","C":"“Route protection” là mô tả chung, không phải tên pattern widget cụ thể trong khóa học.","D":"Middleware thường gắn với backend/web server, không phải pattern widget Flutter chuẩn trong ngữ cảnh này."},
  "Auth route → Guard (chặn trước khi vào màn)."),

Q("SP26-B5-FE", 2,
  "Why are tests important for refactoring?",
  {"A":"Reduce UI work","B":"Ensure changes don't break functionality","C":"Improve animations","D":"Change layout"},
  "B",
  "Vì sao kiểm thử (tests) quan trọng khi refactor code?",
  {"A":"Giảm công việc UI","B":"Đảm bảo thay đổi không làm hỏng chức năng","C":"Cải thiện animation","D":"Đổi layout"},
  "Refactoring là chỉnh sửa cấu trúc code mà không đổi hành vi bên ngoài. Test (unit/widget/integration) là “lưới an toàn” để phát hiện regression sau khi sửa.",
  "Tests xác nhận app vẫn chạy đúng sau khi refactor. Không có test, refactor dễ phá vỡ tính năng mà không biết.",
  {"A":"Test không nhằm giảm công việc UI.","C":"Test không trực tiếp cải thiện animation.","D":"Test không dùng để đổi layout."},
  "Refactor + Test = đổi code an toàn."),

Q("SP26-B5-FE", 3,
  "What is the role of BuildContext in Flutter?",
  {"A":"Store application data","B":"Locate widgets in the widget tree","C":"Manage navigation history","D":"Render UI pixels"},
  "B",
  "Vai trò của BuildContext trong Flutter là gì?",
  {"A":"Lưu dữ liệu ứng dụng","B":"Định vị widget trong cây widget","C":"Quản lý lịch sử điều hướng","D":"Vẽ pixel UI"},
  "BuildContext là “handle” trỏ tới vị trí của một Element trong widget tree. Qua context bạn tìm InheritedWidget (Theme, MediaQuery), Navigator, Scaffold…",
  "BuildContext giúp locate widget/element trong cây để truy cập ancestor (Theme.of(context), Navigator.of(context)). Nó không phải kho state toàn cục.",
  {"A":"Dữ liệu app thường nằm ở State/Provider/BLoC, không phải BuildContext.","C":"Lịch sử navigation do Navigator quản lý.","D":"Render pixel do RenderObject/Engine, không phải BuildContext."},
  "BuildContext = vị trí trong cây widget."),

Q("SP26-B5-FE", 4,
  "What role does the Flutter framework play in application development?",
  {"A":"It manages database servers","B":"It provides UI components and rendering logic","C":"It replaces the operating system","D":"It runs backend business logic"},
  "B",
  "Flutter framework đóng vai trò gì trong phát triển ứng dụng?",
  {"A":"Quản lý database server","B":"Cung cấp thành phần UI và logic render","C":"Thay thế hệ điều hành","D":"Chạy business logic backend"},
  "Flutter framework = toolkit UI + engine render (Skia/Impeller) + widgets/material. Dev viết Dart UI; framework biên dịch thành native view layer.",
  "Flutter cung cấp UI components (widgets) và rendering logic để vẽ giao diện đa nền tảng từ một codebase.",
  {"A":"DB server thuộc backend/infra, không phải vai trò chính của Flutter.","C":"Flutter chạy trên OS, không thay OS.","D":"Business logic backend thường ở server; Flutter là client UI."},
  "Flutter = UI + render, không phải OS/backend DB."),

Q("SP26-B5-FE", 5,
  "How is the Flutter UI constructed internally?",
  {"A":"Using XML layout files","B":"Using HTML and CSS","C":"Using a hierarchical widget tree","D":"Using native UI components only"},
  "C",
  "UI Flutter được xây dựng nội bộ như thế nào?",
  {"A":"Bằng file layout XML","B":"Bằng HTML và CSS","C":"Bằng cây widget phân cấp (hierarchical widget tree)","D":"Chỉ bằng native UI components"},
  "Mọi thứ trong Flutter đều là Widget. UI = cây phân cấp (parent–child). Framework biến widget tree → element tree → render tree.",
  "Flutter dùng hierarchical widget tree: lồng widget con trong widget cha để mô tả UI.",
  {"A":"XML layout là Android View system, không phải Flutter.","B":"HTML/CSS là web DOM, không phải mô hình Flutter.","D":"Flutter tự vẽ bằng engine; không chỉ bọc native controls (dù platform view tồn tại)."},
  "Flutter UI = widget tree phân cấp."),

Q("SP26-B5-FE", 6,
  "Which widget enables custom scroll effects in Flutter?",
  {"A":"ListView","B":"SingleChildScrollView","C":"CustomScrollView","D":"Column"},
  "C",
  "Widget nào cho phép hiệu ứng cuộn tùy biến trong Flutter?",
  {"A":"ListView","B":"SingleChildScrollView","C":"CustomScrollView","D":"Column"},
  "CustomScrollView kết hợp nhiều sliver (SliverAppBar, SliverList…) để tạo scroll phức tạp: collapse app bar, sticky header, mixed lists.",
  "CustomScrollView + slivers = custom scroll effects. ListView/SingleChildScrollView đơn giản hơn, ít linh hoạt khi cần nhiều vùng scroll phối hợp.",
  {"A":"ListView cuộn list chuẩn, ít tùy biến sliver sâu.","B":"SingleChildScrollView cuộn một child, không sliver effects mạnh.","D":"Column không scroll; tràn màn sẽ overflow."},
  "Custom scroll → CustomScrollView + Sliver*."),

Q("SP26-B5-FE", 7,
  "Which practice improves rendering performance?",
  {"A":"Large widget trees","B":"Splitting widgets","C":"Global state","D":"Frequent rebuilds"},
  "B",
  "Thực hành nào cải thiện hiệu năng render?",
  {"A":"Cây widget lớn","B":"Tách nhỏ widget (splitting widgets)","C":"State toàn cục","D":"Rebuild thường xuyên"},
  "Khi setState/rebuild, Flutter rebuild subtree. Tách widget giúp thu hẹp phạm vi rebuild, dùng const, giảm work mỗi frame.",
  "Splitting widgets cải thiện performance vì chỉ phần cần thiết rebuild; dễ const/cache hơn.",
  {"A":"Cây quá lớn → tốn chi phí build/layout.","C":"Global state dễ gây rebuild diện rộng.","D":"Rebuild liên tục là nguyên nhân chậm UI."},
  "Tách widget nhỏ → rebuild ít hơn."),

Q("SP26-B5-FE", 8,
  "What does an integration test verify?",
  {"A":"Single function","B":"Widget rendering","C":"End-to-end app behavior","D":"Theme consistency"},
  "C",
  "Integration test kiểm tra điều gì?",
  {"A":"Một hàm đơn lẻ","B":"Việc render widget","C":"Hành vi end-to-end của app","D":"Tính nhất quán theme"},
  "Ba tầng test Flutter: Unit (hàm/class) → Widget (UI component) → Integration (luồng thật: nhiều màn, plugin, app chạy).",
  "Integration test xác minh end-to-end app behavior: user flow hoàn chỉnh trên app thật/giả lập.",
  {"A":"Single function = unit test.","B":"Widget rendering = widget test.","D":"Theme consistency có thể golden/widget test, không định nghĩa integration test."},
  "Integration = end-to-end flow."),

Q("SP26-B5-FE", 9,
  "Why is separating UI and state logic recommended?",
  {"A":"Reduce code size","B":"Improve maintainability","C":"Faster execution","D":"Better animations"},
  "B",
  "Vì sao nên tách UI và logic state?",
  {"A":"Giảm kích thước code","B":"Cải thiện khả năng bảo trì (maintainability)","C":"Chạy nhanh hơn","D":"Animation đẹp hơn"},
  "Separation of concerns: UI chỉ hiển thị; state/business ở BLoC/Provider/Cubit. Dễ test, tái sử dụng, team làm song song.",
  "Tách UI và state logic giúp maintainability: sửa UI không đụng business; test logic không cần render full UI.",
  {"A":"Đôi khi code files nhiều hơn, không nhất thiết giảm size.","C":"Không phải mục tiêu chính; performance phụ thuộc cách implement.","D":"Animation không phải lý do chính của separation."},
  "UI ⟷ State tách → dễ bảo trì & test."),

Q("SP26-B5-FE", 10,
  "When does Flutter rebuild the widget tree?",
  {"A":"On every frame","B":"When state changes","C":"Only when app restarts","D":"Only during hot restart"},
  "B",
  "Khi nào Flutter rebuild cây widget?",
  {"A":"Mỗi frame","B":"Khi state thay đổi","C":"Chỉ khi app restart","D":"Chỉ khi hot restart"},
  "Reactive UI: khi State.setState, ValueNotifier, BLoC emit state mới… framework đánh dấu dirty và rebuild phần liên quan (không nhất thiết cả app mỗi frame).",
  "Flutter rebuild khi state changes (setState/notifier/stream…). Không rebuild mù quáng mỗi frame trừ khi animation/ticker yêu cầu.",
  {"A":"Không rebuild toàn cây mỗi frame mặc định.","C":"Sai: state đổi runtime cũng rebuild.","D":"Hot restart chỉ là dev tool, không phải điều kiện duy nhất."},
  "State đổi → rebuild UI."),

Q("SP26-B5-FE", 11,
  "Which concept does BLoC heavily rely on?",
  {"A":"Future","B":"Stream","C":"Animation","D":"Theme"},
  "B",
  "BLoC dựa mạnh vào khái niệm nào?",
  {"A":"Future","B":"Stream","C":"Animation","D":"Theme"},
  "BLoC (Business Logic Component): nhận Event → xử lý → phát State qua Stream. UI lắng nghe bằng StreamBuilder/BlocBuilder.",
  "BLoC dựa trên Stream: luồng state bất đồng bộ theo thời gian. Future chỉ one-shot; Stream là chuỗi giá trị liên tục.",
  {"A":"Future dùng nhiều nhưng không phải trụ cột BLoC như Stream.","C":"Animation không liên quan kiến trúc BLoC.","D":"Theme là styling, không phải core BLoC."},
  "BLoC = Event in → Stream of States out."),

Q("SP26-B5-FE", 12,
  "Why is version control critical?",
  {"A":"UI changes","B":"Track and manage code changes","C":"Improve animations","D":"Store data"},
  "B",
  "Vì sao version control quan trọng?",
  {"A":"Thay đổi UI","B":"Theo dõi và quản lý thay đổi code","C":"Cải thiện animation","D":"Lưu dữ liệu"},
  "Version control (Git) lưu lịch sử commit, nhánh, merge, rollback, collaboration. Không có VCS thì khó team và khó khôi phục lỗi.",
  "Version control giúp track & manage code changes: ai sửa gì, khi nào, revert an toàn.",
  {"A":"UI changes chỉ là một loại change, không phải lý do tồn tại VCS.","C":"Không liên quan animation.","D":"Store data app là DB/storage, không phải Git."},
  "Git = lịch sử & phối hợp code."),

Q("SP26-B5-FE", 13,
  "Why is immutability important in BLoC states?",
  {"A":"UI speed","B":"Predictable state changes","C":"Memory usage","D":"Theme control"},
  "B",
  "Vì sao immutability quan trọng với state của BLoC?",
  {"A":"Tốc độ UI","B":"Thay đổi state có tính dự đoán (predictable)","C":"Dùng bộ nhớ","D":"Điều khiển theme"},
  "Immutable state: mỗi thay đổi tạo object state mới thay vì mutate. Dễ so sánh (equatable), debug, time-travel; tránh side-effect ẩn.",
  "Immutability làm state changes predictable: biết chính xác state trước/sau, UI rebuild dựa trên state mới rõ ràng.",
  {"A":"Không phải mục tiêu chính (đôi khi copy object còn tốn hơn).","C":"Không nhằm tối ưu memory trước hết.","D":"Không liên quan theme."},
  "State BLoC: immutable → dễ đoán & so sánh."),

Q("SP26-B5-FE", 14,
  "Which Flutter plugin provides SQLite support?",
  {"A":"hive","B":"moor","C":"sqflite","D":"shared_preferences"},
  "C",
  "Plugin Flutter nào cung cấp hỗ trợ SQLite?",
  {"A":"hive","B":"moor","C":"sqflite","D":"shared_preferences"},
  "SQLite là DB quan hệ nhúng trên device. Package sqflite là bridge Flutter phổ biến tới SQLite. (drift/moor là ORM trên SQLite; hive là NoSQL key-value).",
  "sqflite cung cấp SQLite support trực tiếp. Moor/Drift là abstraction; hive/shared_preferences không phải SQLite.",
  {"A":"Hive = local NoSQL, không phải SQLite.","B":"Moor (Drift) là ORM; câu hỏi nhấn plugin SQLite phổ biến = sqflite.","D":"shared_preferences chỉ key-value đơn giản."},
  "SQLite trên Flutter → sqflite."),

Q("SP26-B5-FE", 15,
  "What is the main benefit of using Maps in Dart?",
  {"A":"Storing values without keys","B":"Storing key-value pairs","C":"Rendering UI components","D":"Managing asynchronous tasks"},
  "B",
  "Lợi ích chính của Map trong Dart là gì?",
  {"A":"Lưu giá trị không cần key","B":"Lưu các cặp key–value","C":"Render UI","D":"Quản lý tác vụ bất đồng bộ"},
  "Map<K,V> là cấu trúc ánh xạ khóa → giá trị (như dictionary). Tra cứu theo key O(1) trung bình với HashMap.",
  "Map dùng để store key-value pairs: ví dụ {\"id\": 1, \"name\": \"An\"}.",
  {"A":"Không key thì là List/Set, không phải Map.","C":"Render UI là việc của Widget.","D":"Async là Future/Stream/async-await."},
  "Map = key → value."),

Q("SP26-B5-FE", 16,
  "Which tool helps analyze UI performance in Flutter?",
  {"A":"Inspector","B":"DevTools","C":"Emulator","D":"Hot reload"},
  "B",
  "Công cụ nào giúp phân tích hiệu năng UI trong Flutter?",
  {"A":"Inspector","B":"DevTools","C":"Emulator","D":"Hot reload"},
  "Flutter DevTools: suite debug (Inspector, CPU/memory, performance overlay, network…). Dùng để phân tích jank, rebuild, frame time.",
  "DevTools là bộ công cụ phân tích UI performance. Widget Inspector nằm trong DevTools nhưng “tool” tổng quát cho performance là DevTools.",
  {"A":"Inspector chủ yếu xem cây widget/layout, không đủ nghĩa “analyze performance” như DevTools.","C":"Emulator chỉ môi trường chạy.","D":"Hot reload là dev productivity, không phải profiler."},
  "Chậm UI → mở Flutter DevTools."),

Q("SP26-B5-FE", 17,
  "What does a Dart class primarily represent?",
  {"A":"A UI widget only","B":"A blueprint for creating objects","C":"A database table","D":"A network request"},
  "B",
  "Class trong Dart chủ yếu đại diện cho điều gì?",
  {"A":"Chỉ một UI widget","B":"Bản thiết kế (blueprint) để tạo object","C":"Một bảng database","D":"Một network request"},
  "OOP: class = khuôn mẫu (fields + methods); object/instance = thực thể tạo từ class bằng constructor.",
  "Class là blueprint for creating objects — nền tảng OOP của Dart.",
  {"A":"Widget cũng là class, nhưng class không chỉ cho UI.","C":"Table là khái niệm DB.","D":"Network request là hành vi/API, không định nghĩa class."},
  "Class = khuôn → Object = instance."),

Q("SP26-B5-FE", 18,
  "What is the purpose of SliverAppBar?",
  {"A":"Static app bar","B":"Scrollable flexible app bar","C":"Bottom navigation","D":"Drawer control"},
  "B",
  "Mục đích của SliverAppBar là gì?",
  {"A":"App bar tĩnh","B":"App bar linh hoạt, cuộn được","C":"Điều hướng dưới","D":"Điều khiển Drawer"},
  "SliverAppBar dùng trong CustomScrollView: có thể expand/collapse, pin, floating khi user scroll.",
  "SliverAppBar = scrollable flexible app bar tích hợp scroll view (sliver).",
  {"A":"AppBar thường cố định hơn; “static” không mô tả đúng strength của SliverAppBar.","C":"BottomNavigationBar là nav dưới.","D":"Drawer là menu trượt bên."},
  "Scroll + app bar co giãn → SliverAppBar."),

Q("SP26-B5-FE", 19,
  "What is Hive mainly used for?",
  {"A":"Remote database","B":"Lightweight local NoSQL storage","C":"State management","D":"Routing"},
  "B",
  "Hive chủ yếu dùng để làm gì?",
  {"A":"Database từ xa","B":"Lưu trữ NoSQL local nhẹ","C":"Quản lý state","D":"Điều hướng"},
  "Hive: key-value NoSQL cực nhẹ, chạy thuần Dart, phù hợp cache/settings/offline nhỏ, nhanh hơn SQLite cho use-case đơn giản.",
  "Hive = lightweight local NoSQL storage trên device.",
  {"A":"Remote DB là server (Firebase, Postgres…).","C":"State management là Provider/BLoC/Riverpod.","D":"Routing là Navigator/GoRouter."},
  "Hive = NoSQL local nhẹ."),

Q("SP26-B5-FE", 20,
  "Which HTTP header is commonly used for authorization?",
  {"A":"Content-Type","B":"Accept","C":"Authorization","D":"Cache-Control"},
  "C",
  "HTTP header nào thường dùng cho authorization?",
  {"A":"Content-Type","B":"Accept","C":"Authorization","D":"Cache-Control"},
  "Header Authorization mang credential (thường Bearer <token>). Server đọc header để xác thực request API.",
  "Authorization header dùng gửi token/credentials. Ví dụ: Authorization: Bearer eyJhbGciOi...",
  {"A":"Content-Type mô tả kiểu body (JSON…).","B":"Accept cho biết client muốn nhận format nào.","D":"Cache-Control điều khiển cache."},
  "Auth token → header Authorization."),

Q("SP26-B5-FE", 21,
  "What does TextEditingController manage?",
  {"A":"Theme","B":"Text input value","C":"Validation rules","D":"Layout constraints"},
  "B",
  "TextEditingController quản lý gì?",
  {"A":"Theme","B":"Giá trị văn bản nhập","C":"Luật validation","D":"Ràng buộc layout"},
  "TextEditingController gắn với TextField/TextFormField: đọc/ghi text, selection, listen thay đổi; cần dispose để tránh leak.",
  "TextEditingController manage text input value (và selection) của ô nhập.",
  {"A":"Theme do ThemeData.","C":"Validation thường Form/validator functions.","D":"Constraints do layout widgets (SizedBox, Expanded….)."},
  "Controller text = TextEditingController."),

Q("SP26-B5-FE", 22,
  "Why is Dart considered suitable for Flutter development?",
  {"A":"It is only used for backend systems","B":"It supports both UI and application logic efficiently","C":"It replaces native languages","D":"It does not support asynchronous programming"},
  "B",
  "Vì sao Dart phù hợp phát triển Flutter?",
  {"A":"Chỉ dùng cho backend","B":"Hỗ trợ hiệu quả cả UI và logic ứng dụng","C":"Thay thế ngôn ngữ native","D":"Không hỗ trợ lập trình bất đồng bộ"},
  "Dart: OOP, null-safety, async/await, AOT/JIT (hot reload + release nhanh), được thiết kế gắn với Flutter UI model.",
  "Dart phù hợp vì handle cả UI declaration và app logic trong một ngôn ngữ, hiệu quả với Flutter tooling.",
  {"A":"Dart không chỉ backend.","C":"Không thay thế hoàn toàn Kotlin/Swift; compile ra native code/engine.","D":"Sai: Dart hỗ trợ async mạnh."},
  "Dart = UI + logic cho Flutter."),

Q("SP26-B5-FE", 23,
  "What does the build() method return in a widget?",
  {"A":"A screen","B":"A widget tree describing the UI","C":"Application state","D":"Rendered pixels"},
  "B",
  "Phương thức build() của widget trả về gì?",
  {"A":"Một màn hình","B":"Cây widget mô tả UI","C":"State ứng dụng","D":"Các pixel đã render"},
  "build(BuildContext) → Widget (thường là cây con). Framework gọi build khi cần cập nhật UI description; chưa phải pixels cuối.",
  "build() trả về widget tree describing the UI — mô tả declarative, chưa phải frame đã vẽ.",
  {"A":"Screen là khái niệm UX; build trả Widget.","C":"State nằm ở State object / state managers.","D":"Pixels do render pipeline sau build/layout/paint."},
  "build() → Widget (mô tả UI)."),

Q("SP26-B5-FE", 24,
  "What represents the output of a BLoC?",
  {"A":"Events","B":"Widgets","C":"States","D":"Controllers"},
  "C",
  "Output của BLoC là gì?",
  {"A":"Events","B":"Widgets","C":"States","D":"Controllers"},
  "Luồng BLoC: UI gửi Events → BLoC xử lý → emit States → UI rebuild theo state.",
  "Output của BLoC là States. Events là input; widgets thuộc UI layer.",
  {"A":"Events là đầu vào.","B":"Widgets thuộc presentation, không phải output BLoC.","D":"Controller là khái niệm khác (TextEditingController, GetX….)."},
  "BLoC: Event → State."),

Q("SP26-B5-FE", 25,
  "What is Cubit in BLoC?",
  {"A":"UI widget","B":"Simplified BLoC without events","C":"Database layer","D":"Animation helper"},
  "B",
  "Cubit trong BLoC là gì?",
  {"A":"Widget UI","B":"BLoC rút gọn không dùng events","C":"Tầng database","D":"Helper animation"},
  "Cubit extends BlocBase: gọi emit(state) trực tiếp từ methods, không cần Event classes. Nhẹ hơn BLoC đầy đủ khi flow đơn giản.",
  "Cubit = simplified BLoC without events — vẫn reactive state stream nhưng API đơn giản hơn.",
  {"A":"Không phải widget.","C":"Không phải DB layer.","D":"Không phải animation helper."},
  "Cubit = BLoC gọn, không Event."),

Q("SP26-B5-FE", 26,
  "Which activity is typically performed after creating a new Flutter project?",
  {"A":"Deploying to app stores","B":"Running the default app on a device","C":"Configuring authentication","D":"Optimizing database queries"},
  "B",
  "Việc nào thường làm ngay sau khi tạo project Flutter mới?",
  {"A":"Deploy lên store","B":"Chạy app mặc định trên thiết bị/emulator","C":"Cấu hình authentication","D":"Tối ưu truy vấn DB"},
  "flutter create → flutter run: verify SDK, device, hot reload. Counter demo mặc định xác nhận môi trường OK.",
  "Sau create project, bước điển hình là run default app on device/emulator.",
  {"A":"Deploy là bước cuối lifecycle.","C":"Auth cấu hình khi có yêu cầu tính năng.","D":"DB optimize không phải bước đầu."},
  "create → run demo app trước."),

Q("SP26-B5-FE", 27,
  "Which practice improves deployment security?",
  {"A":"Debug builds","B":"Secure signing keys","C":"Hardcoding secrets","D":"Skipping validation"},
  "B",
  "Thực hành nào cải thiện bảo mật khi deploy?",
  {"A":"Bản build debug","B":"Bảo vệ khóa ký (secure signing keys)","C":"Hardcode secrets","D":"Bỏ validation"},
  "App signing key (keystore/Play App Signing) chứng thực bản phát hành. Lộ key = kẻ tấn công ký malware giả mạo app.",
  "Secure signing keys (và không hardcode secrets) là best practice deployment security.",
  {"A":"Debug build không phải bản production an toàn.","C":"Hardcode secrets là anti-pattern nguy hiểm.","D":"Skip validation làm yếu bảo mật."},
  "Deploy an toàn → giữ keystore/secrets chặt."),

Q("SP26-B5-FE", 28,
  "Why is Chapter 14 considered optional (Plus)?",
  {"A":"Deployment is UI logic","B":"Apps can be tested without publishing","C":"It replaces authentication","D":"It handles APIs"},
  "B",
  "Vì sao Chapter 14 được coi là optional (Plus)?",
  {"A":"Deploy là logic UI","B":"App có thể được kiểm thử mà không cần publish","C":"Nó thay authentication","D":"Nó xử lý API"},
  "Chương Plus về publish/deploy: hữu ích nhưng không chặn việc học core Flutter — vẫn dev/test local/emulator.",
  "Optional vì apps can be tested without publishing; deployment là bước nâng cao sau khi app đã chạy ổn.",
  {"A":"Deploy không phải UI logic.","C":"Không thay authentication.","D":"API thường thuộc chương networking, không phải lý do optional ch.14."},
  "Plus deploy: học sau, test local vẫn được."),

Q("SP26-B5-FE", 29,
  "What is the primary purpose of ThemeData in Flutter?",
  {"A":"Manage navigation","B":"Define application-wide visual styles","C":"Handle state changes","D":"Control animations"},
  "B",
  "Mục đích chính của ThemeData trong Flutter là gì?",
  {"A":"Quản lý navigation","B":"Định nghĩa style giao diện toàn app","C":"Xử lý thay đổi state","D":"Điều khiển animation"},
  "ThemeData (MaterialApp.theme) gom colors, typography, component themes. Widget dùng Theme.of(context) để thống nhất brand UI.",
  "ThemeData define application-wide visual styles — một nơi chỉnh màu/font cho cả app.",
  {"A":"Navigation là Navigator/Router.","C":"State là setState/BLoC…","D":"Animation là AnimationController/implicit widgets."},
  "ThemeData = skin toàn app."),

Q("SP26-B5-FE", 30,
  "Which method is used to update the UI when state changes?",
  {"A":"build()","B":"setState()","C":"initState()","D":"dispose()"},
  "B",
  "Phương thức nào dùng để cập nhật UI khi state đổi (trong StatefulWidget)?",
  {"A":"build()","B":"setState()","C":"initState()","D":"dispose()"},
  "setState(() { ... }) đánh dấu State dirty → schedule rebuild → gọi build() lại. build() chỉ mô tả UI; setState kích hoạt cập nhật.",
  "setState() là API cập nhật UI khi local state đổi trong StatefulWidget.",
  {"A":"build() được framework gọi; dev không “gọi build để update”.","C":"initState chạy 1 lần khi tạo State.","D":"dispose dọn resource khi hủy."},
  "Đổi state local → setState()."),

Q("SP26-B5-FE", 31,
  "Which Flutter package is commonly used for simple key-value storage?",
  {"A":"sqflite","B":"shared_preferences","C":"provider","D":"http"},
  "B",
  "Package nào thường dùng để lưu key–value đơn giản?",
  {"A":"sqflite","B":"shared_preferences","C":"provider","D":"http"},
  "shared_preferences bọc NSUserDefaults/SharedPreferences: lưu bool/int/string nhỏ (settings, flags). Không thay DB phức tạp.",
  "shared_preferences = simple key-value local storage phổ biến.",
  {"A":"sqflite là SQL database.","C":"provider là state management.","D":"http là gọi API mạng."},
  "Settings nhỏ → shared_preferences."),

Q("SP26-B5-FE", 32,
  "Why should architecture be decided early?",
  {"A":"Avoid UI work","B":"Reduce refactoring cost","C":"Improve animations","D":"Change theme"},
  "B",
  "Vì sao nên quyết định architecture sớm?",
  {"A":"Tránh làm UI","B":"Giảm chi phí refactor sau này","C":"Cải thiện animation","D":"Đổi theme"},
  "Architecture (layering, state management, folder structure) định hướng scale. Chọn muộn → rewrite tốn kém (technical debt).",
  "Quyết định sớm reduce refactoring cost khi app lớn và team mở rộng.",
  {"A":"Vẫn phải làm UI.","C":"Không liên quan trực tiếp animation.","D":"Theme dễ đổi hơn architecture."},
  "Architecture sớm = bớt đau sau."),

Q("SP26-B5-FE", 33,
  "What is pagination used for?",
  {"A":"UI animation","B":"Handling large datasets efficiently","C":"Theme management","D":"Authentication"},
  "B",
  "Pagination dùng để làm gì?",
  {"A":"Animation UI","B":"Xử lý dataset lớn một cách hiệu quả","C":"Quản lý theme","D":"Xác thực"},
  "Pagination: tải dữ liệu theo trang/chunk (page 1,2,3…) thay vì load hết — giảm memory, network, time-to-first-content.",
  "Pagination handles large datasets efficiently bằng cách chia nhỏ lần tải.",
  {"A":"Không phải animation.","C":"Không phải theme.","D":"Không phải auth."},
  "List dài → phân trang (pagination)."),

Q("SP26-B5-FE", 34,
  "Which widget helps avoid rebuilding unchanged UI parts?",
  {"A":"Container","B":"RepaintBoundary","C":"Column","D":"FutureBuilder"},
  "B",
  "Widget nào giúp tránh vẽ lại/ảnh hưởng phần UI không đổi?",
  {"A":"Container","B":"RepaintBoundary","C":"Column","D":"FutureBuilder"},
  "RepaintBoundary tạo layer repaint riêng: khi vùng khác repaint, vùng trong boundary có thể không cần repaint lại. Hữu ích với animation/list phức tạp. (Lưu ý: rebuild ≠ repaint; nhưng trong các lựa chọn đây là đáp án performance isolation.)",
  "RepaintBoundary cô lập vùng paint, giảm work khi phần khác của UI cập nhật — giúp phần không đổi ít bị ảnh hưởng hơn.",
  {"A":"Container là layout/decoration generic.","C":"Column chỉ xếp dọc.","D":"FutureBuilder rebuild theo Future, không phải công cụ tối ưu phần không đổi."},
  "Tối ưu paint → RepaintBoundary."),

Q("SP26-B5-FE", 35,
  "Which widget is used to handle asynchronous API responses in UI?",
  {"A":"FutureBuilder","B":"ListView","C":"Provider","D":"Form"},
  "A",
  "Widget nào dùng để xử lý phản hồi API bất đồng bộ trên UI?",
  {"A":"FutureBuilder","B":"ListView","C":"Provider","D":"Form"},
  "FutureBuilder lắng nghe một Future (http.get…): snapshot có waiting/data/error để render loading/success/fail.",
  "FutureBuilder handle async API response trong UI một cách declarative.",
  {"B":"ListView chỉ hiển thị danh sách.","C":"Provider quản lý state, không thay FutureBuilder trực tiếp.","D":"Form cho nhập liệu/validate."},
  "Future API → FutureBuilder."),

Q("SP26-B5-FE", 36,
  "Which Dart feature helps organize code into reusable libraries?",
  {"A":"Widgets","B":"Packages and imports","C":"Hot reload","D":"Layout constraints"},
  "B",
  "Tính năng Dart nào giúp tổ chức code thành thư viện tái sử dụng?",
  {"A":"Widgets","B":"Packages và imports","C":"Hot reload","D":"Ràng buộc layout"},
  "package: và import cho phép modularize: lib/, pub.dev packages, export public API — tái sử dụng xuyên project.",
  "Packages and imports tổ chức & tái sử dụng libraries.",
  {"A":"Widgets là UI building blocks, không phải hệ thống package.","C":"Hot reload là dev tool.","D":"Constraints là layout system."},
  "Tái sử dụng code → package + import."),

Q("SP26-B5-FE", 37,
  "What is refresh token used for?",
  {"A":"UI refresh","B":"Extend session without re-login","C":"Theme update","D":"Navigation reset"},
  "B",
  "Refresh token dùng để làm gì?",
  {"A":"Làm mới UI","B":"Gia hạn phiên mà không cần đăng nhập lại","C":"Cập nhật theme","D":"Reset navigation"},
  "OAuth-style: access token ngắn hạn gọi API; refresh token dài hơn để xin access token mới — UX liền mạch, bảo mật tốt hơn chỉ 1 token sống mãi.",
  "Refresh token extend session without re-login bằng cách lấy access token mới.",
  {"A":"Không liên quan setState UI.","C":"Không phải theme.","D":"Không reset navigation."},
  "Access hết hạn → refresh token xin token mới."),

Q("SP26-B5-FE", 38,
  "What is rebuild scope optimization in Flutter?",
  {"A":"Reducing widget tree depth","B":"Limiting rebuild to affected widgets","C":"Caching API responses","D":"Using global state"},
  "B",
  "Tối ưu phạm vi rebuild trong Flutter là gì?",
  {"A":"Giảm độ sâu cây widget","B":"Giới hạn rebuild chỉ tới widget bị ảnh hưởng","C":"Cache phản hồi API","D":"Dùng global state"},
  "Rebuild scope: chỉ rebuild subtree cần thiết (tách widget, Selector, BlocSelector, const, keys) thay vì cả màn hình.",
  "Rebuild scope optimization = limiting rebuild to affected widgets — core performance practice.",
  {"A":"Giảm depth có thể giúp nhưng không định nghĩa “rebuild scope”.","C":"API cache là data layer.","D":"Global state thường làm scope rộng hơn, ngược tối ưu."},
  "Rebuild hẹp = app mượt."),

Q("SP26-B5-FE", 39,
  "Why is BLoC suitable for large teams?",
  {"A":"Less code","B":"Standardized architecture","C":"Faster builds","D":"UI reuse"},
  "B",
  "Vì sao BLoC phù hợp team lớn?",
  {"A":"Ít code hơn","B":"Kiến trúc chuẩn hóa","C":"Build nhanh hơn","D":"Tái sử dụng UI"},
  "BLoC ép convention: events/states/folders rõ. Team lớn cần shared patterns để onboarding và review nhất quán.",
  "BLoC mang standardized architecture — nhiều người follow cùng pattern.",
  {"A":"BLoC thường nhiều boilerplate hơn Cubit/setState.","C":"Không làm compiler nhanh hơn.","D":"UI reuse là widget composition, không phải lý do chính BLoC cho team lớn."},
  "Team lớn → cần chuẩn (BLoC)."),

Q("SP26-B5-FE", 40,
  "Which widget reacts to async data from local storage?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Provider"},
  "A",
  "Widget nào phản ứng với dữ liệu bất đồng bộ từ local storage?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Provider"},
  "shared_preferences/Hive get thường trả Future → FutureBuilder. StreamBuilder dành cho Stream (realtime). Provider là DI/state, không “react Future” sẵn.",
  "Async one-shot từ local storage → FutureBuilder là lựa chọn trực tiếp trên UI.",
  {"B":"StreamBuilder cần Stream; local storage get thường Future.","C":"ListView chỉ list UI.","D":"Provider không tự lắng nghe Future storage."},
  "prefs.get → Future → FutureBuilder."),

Q("SP26-B5-FE", 41,
  "What is a token in authentication systems?",
  {"A":"UI key","B":"Temporary access credential","C":"Database ID","D":"Theme value"},
  "B",
  "Token trong hệ thống authentication là gì?",
  {"A":"Khóa UI","B":"Chứng chỉ truy cập tạm thời","C":"ID database","D":"Giá trị theme"},
  "Token (JWT/opaque) là chuỗi credential server cấp sau login; client gửi kèm request để chứng minh đã xác thực, thường có expiry.",
  "Token = temporary access credential cho API/session.",
  {"A":"Không phải UI key.","C":"Không đồng nghĩa primary key DB.","D":"Không liên quan theme."},
  "Login xong nhận token → gọi API."),

Q("SP26-B5-FE", 42,
  "What does a Tween define?",
  {"A":"Animation speed","B":"Value range for animation","C":"UI layout","D":"State logic"},
  "B",
  "Tween định nghĩa gì?",
  {"A":"Tốc độ animation","B":"Khoảng giá trị cho animation","C":"Layout UI","D":"Logic state"},
  "Tween<T> nội suy từ begin → end (Color, double, Offset…). Controller (0→1) * Tween = giá trị hiện tại. Speed do duration/curve quyết định.",
  "Tween define value range (begin/end) cho animation.",
  {"A":"Tốc độ/duration thuộc AnimationController/Duration.","C":"Layout là widget constraints.","D":"State logic là BLoC/setState."},
  "Tween = from → to."),

Q("SP26-B5-FE", 43,
  "Which Dart feature allows defining reusable, type-safe components?",
  {"A":"Mixins","B":"Generics","C":"Futures","D":"Streams"},
  "B",
  "Tính năng Dart nào cho phép định nghĩa thành phần tái sử dụng, an toàn kiểu?",
  {"A":"Mixins","B":"Generics","C":"Futures","D":"Streams"},
  "Generics: List<T>, Map<K,V>, class Box<T> — tái sử dụng thuật toán/cấu trúc với type safety compile-time.",
  "Generics = reusable + type-safe components/collections.",
  {"A":"Mixin tái sử dụng behavior, không nhấn type parameter.","C":"Future là async one-shot.","D":"Stream là async sequence."},
  "List<int>, Repository<T> → Generics."),

Q("SP26-B5-FE", 44,
  "Which widget animates between two widgets?",
  {"A":"AnimatedSwitcher","B":"AnimatedOpacity","C":"AnimatedAlign","D":"AnimatedSize"},
  "A",
  "Widget nào animate chuyển giữa hai widget?",
  {"A":"AnimatedSwitcher","B":"AnimatedOpacity","C":"AnimatedAlign","D":"AnimatedSize"},
  "AnimatedSwitcher khi child đổi identity sẽ transition (fade/scale…) giữa widget cũ và mới.",
  "AnimatedSwitcher animates between two widgets khi child được thay thế.",
  {"B":"AnimatedOpacity chỉ đổi độ mờ một child.","C":"AnimatedAlign animate alignment.","D":"AnimatedSize animate kích thước."},
  "Đổi widget A→B mượt → AnimatedSwitcher."),

Q("SP26-B5-FE", 45,
  "Why should setState() be called sparingly?",
  {"A":"It increases app size","B":"It may trigger unnecessary rebuilds","C":"It blocks UI thread","D":"It causes memory leaks"},
  "B",
  "Vì sao nên gọi setState() một cách hạn chế/cẩn thận?",
  {"A":"Làm tăng size app","B":"Có thể gây rebuild không cần thiết","C":"Chặn UI thread","D":"Gây memory leak"},
  "Mỗi setState rebuild subtree State đó. Gọi quá nhiều/phạm vi rộng → jank. Nên setState hẹp, hoặc dùng state management granular.",
  "setState sparingly vì may trigger unnecessary rebuilds.",
  {"A":"Không làm tăng binary size.","C":"setState không block theo nghĩa sync long task (nhưng rebuild nặng gây jank).","D":"Leak thường do controller/stream không dispose, không phải setState."},
  "setState ít & đúng chỗ."),

Q("SP26-B5-FE", 46,
  "What is test isolation?",
  {"A":"Running all tests together","B":"Independence of test cases","C":"UI separation","D":"Mocking only"},
  "B",
  "Test isolation là gì?",
  {"A":"Chạy tất cả test cùng lúc","B":"Sự độc lập giữa các test case","C":"Tách UI","D":"Chỉ mocking"},
  "Isolation: mỗi test tự setup/teardown, không phụ thuộc thứ tự hay side-effect test khác — kết quả ổn định, dễ debug.",
  "Test isolation = independence of test cases.",
  {"A":"Chạy cùng lúc không phải định nghĩa isolation.","C":"UI separation là kiến trúc app.","D":"Mocking hỗ trợ isolation nhưng không đồng nghĩa isolation."},
  "Test độc lập = isolation."),

Q("SP26-B5-FE", 47,
  "What does crossAxisAlignment control?",
  {"A":"Vertical alignment in Column","B":"Horizontal alignment in Column","C":"Child order","D":"Widget size"},
  "B",
  "crossAxisAlignment điều khiển gì?",
  {"A":"Căn dọc trong Column","B":"Căn ngang trong Column","C":"Thứ tự con","D":"Kích thước widget"},
  "Flex: main axis = hướng chính (Column = dọc, Row = ngang); cross axis = vuông góc. crossAxisAlignment căn trên trục phụ. Trong Column: cross = ngang (start/center/end/stretch).",
  "Trong Column, crossAxisAlignment control horizontal alignment of children.",
  {"A":"Căn dọc Column là mainAxisAlignment.","C":"Order do thứ tự children.","D":"Size do constraints/child."},
  "Column: main=dọc, cross=ngang."),

Q("SP26-B5-FE", 48,
  "Which tool is commonly used for version control?",
  {"A":"SVN","B":"Git","C":"FTP","D":"ZIP"},
  "B",
  "Công cụ nào thường dùng cho version control?",
  {"A":"SVN","B":"Git","C":"FTP","D":"ZIP"},
  "Git là DVCS phổ biến nhất hiện nay (GitHub/GitLab). SVN là VCS cũ hơn; FTP/ZIP không phải version control đúng nghĩa.",
  "Git là tool version control phổ biến nhất trong industry và khóa học hiện đại.",
  {"A":"SVN tồn tại nhưng không “commonly” như Git ngày nay.","C":"FTP truyền file, không history commit.","D":"ZIP chỉ nén file."},
  "Version control → Git."),
]

FE: list[dict] = [
Q("SP26-FE", 1,
  "Why is clean architecture beneficial?",
  {"A":"Fewer files","B":"Easier maintenance and testing","C":"Better UI","D":"Faster builds"},
  "B",
  "Vì sao clean architecture mang lại lợi ích?",
  {"A":"Ít file hơn","B":"Dễ bảo trì và kiểm thử hơn","C":"UI đẹp hơn","D":"Build nhanh hơn"},
  "Clean Architecture tách lớp (UI / domain / data), dependency hướng vào business rules. Code dễ test, đổi UI/DB không phá core.",
  "Lợi ích chính: easier maintenance and testing nhờ tách concern rõ, không phải “ít file” hay “UI đẹp”.",
  {"A":"Thường có nhiều file/layer hơn.","C":"UI quality không phải mục tiêu trực tiếp.","D":"Build time không cải thiện từ architecture pattern."},
  "Clean Arch → dễ test & bảo trì."),

Q("SP26-FE", 2,
  "What is Dart primarily designed for in the Flutter ecosystem?",
  {"A":"Database management","B":"User interface development","C":"General-purpose programming with UI focus","D":"Network security"},
  "C",
  "Trong hệ sinh thái Flutter, Dart chủ yếu được thiết kế cho mục đích gì?",
  {"A":"Quản trị database","B":"Chỉ phát triển UI","C":"Lập trình đa mục đích, chú trọng UI","D":"Bảo mật mạng"},
  "Dart là general-purpose language (client/server) nhưng tối ưu tooling cho UI reactive (Flutter): hot reload, sound null safety, isolates.",
  "Đáp án chuẩn: general-purpose programming with UI focus — vừa logic app vừa UI, không chỉ một mảng.",
  {"A":"Không phải DB engine.","B":"Không chỉ UI; còn logic/business.","D":"Không phải ngôn ngữ chuyên network security."},
  "Dart = general purpose + UI-friendly."),

Q("SP26-FE", 3,
  "Why is secure authentication critical in mobile apps?",
  {"A":"UI quality","B":"Protect user data","C":"Reduce code","D":"Improve speed"},
  "B",
  "Vì sao authentication an toàn quan trọng với mobile app?",
  {"A":"Chất lượng UI","B":"Bảo vệ dữ liệu người dùng","C":"Giảm code","D":"Tăng tốc"},
  "Authentication xác minh danh tính; authorization phân quyền. Mobile lưu token/session — lỗ hổng auth = lộ PII, giao dịch, account takeover.",
  "Secure auth critical để protect user data và tài nguyên API.",
  {"A":"Không liên quan độ đẹp UI.","C":"Auth thường thêm code, không giảm.","D":"Không nhằm tăng tốc app."},
  "Auth chặt = bảo vệ data user."),

Q("SP26-FE", 4,
  "Which HTTP method is typically used to retrieve data?",
  {"A":"POST","B":"PUT","C":"GET","D":"DELETE"},
  "C",
  "HTTP method nào thường dùng để lấy dữ liệu?",
  {"A":"POST","B":"PUT","C":"GET","D":"DELETE"},
  "REST: GET đọc tài nguyên (safe/idempotent); POST tạo; PUT/PATCH cập nhật; DELETE xóa.",
  "Retrieve data → GET.",
  {"A":"POST gửi body tạo/xử lý, không phải retrieve chuẩn.","B":"PUT cập nhật/thay thế.","D":"DELETE xóa."},
  "Đọc API → GET."),

Q("SP26-FE", 5,
  "What happens if a non-nullable variable is not initialized in Dart?",
  {"A":"The app runs normally","B":"A runtime exception occurs","C":"A compile-time error occurs","D":"The value becomes null automatically"},
  "C",
  "Điều gì xảy ra nếu biến non-nullable không được khởi tạo trong Dart?",
  {"A":"App chạy bình thường","B":"Lỗi runtime","C":"Lỗi compile-time","D":"Tự thành null"},
  "Sound null safety: biến kiểu T (không T?) phải chắc chắn được gán trước khi dùng — compiler bắt lỗi sớm.",
  "Non-nullable chưa init → compile-time error (không chờ runtime).",
  {"A":"Không compile được thì không “chạy bình thường”.","B":"Mục tiêu null safety là bắt từ compile.","D":"Non-nullable không tự null."},
  "Non-null chưa gán → lỗi biên dịch."),

Q("SP26-FE", 6,
  "Which command builds a release APK?",
  {"A":"flutter run","B":"flutter build apk","C":"flutter doctor","D":"flutter clean"},
  "B",
  "Lệnh nào build APK bản release?",
  {"A":"flutter run","B":"flutter build apk","C":"flutter doctor","D":"flutter clean"},
  "flutter build apk tạo artifact Android (debug/release tùy flag, mặc định release). flutter run chạy dev; doctor kiểm tra env; clean xóa build cache.",
  "Build release APK → flutter build apk.",
  {"A":"run = chạy dev.","C":"doctor = chẩn đoán SDK.","D":"clean = dọn build."},
  "APK release → flutter build apk."),

Q("SP26-FE", 7,
  "Which widget allows overlapping of its child widgets?",
  {"A":"Column","B":"Row","C":"Stack","D":"Expanded"},
  "C",
  "Widget nào cho phép các widget con chồng lên nhau?",
  {"A":"Column","B":"Row","C":"Stack","D":"Expanded"},
  "Stack xếp children theo lớp (z-order), dùng Positioned để đặt tọa độ — badge, overlay, watermark.",
  "Overlap children → Stack.",
  {"A":"Column xếp dọc không chồng.","B":"Row xếp ngang.","D":"Expanded chiếm không gian flex, không chồng."},
  "Chồng lớp UI → Stack."),

Q("SP26-FE", 8,
  "Which platforms can Flutter applications target using a single codebase?",
  {"A":"Android only","B":"iOS only","C":"Android, iOS, web, and desktop","D":"Web servers only"},
  "C",
  "Flutter app với một codebase có thể nhắm tới những nền tảng nào?",
  {"A":"Chỉ Android","B":"Chỉ iOS","C":"Android, iOS, web và desktop","D":"Chỉ web server"},
  "Flutter multi-platform: mobile (Android/iOS), web, desktop (Windows/macOS/Linux) từ Dart UI codebase chung.",
  "Single codebase → Android, iOS, web, and desktop.",
  {"A":"Không chỉ Android.","B":"Không chỉ iOS.","D":"Không phải backend server framework."},
  "Flutter = multi-platform UI."),

Q("SP26-FE", 9,
  "What is the main risk of improper state management?",
  {"A":"UI inconsistency","B":"Longer compile time","C":"Package conflicts","D":"Build errors"},
  "A",
  "Rủi ro chính của quản lý state sai cách là gì?",
  {"A":"UI không nhất quán","B":"Compile lâu hơn","C":"Xung đột package","D":"Lỗi build"},
  "State sai/out-of-sync → UI hiện data cũ, màn khác nhau lệch, bug khó tái hiện. Đây là rủi ro chức năng/UX cốt lõi.",
  "Improper state management → UI inconsistency.",
  {"B":"Compile time ít liên quan pattern state.","C":"Package conflict là dependency issue.","D":"Build errors là compile/config."},
  "State loạn → UI lệch."),

Q("SP26-FE", 10,
  "What does CurvedAnimation provide?",
  {"A":"Layout control","B":"Animation curve behavior","C":"State updates","D":"Navigation"},
  "B",
  "CurvedAnimation cung cấp gì?",
  {"A":"Điều khiển layout","B":"Hành vi đường cong animation","C":"Cập nhật state","D":"Điều hướng"},
  "CurvedAnimation bọc parent Animation + Curve (easeIn, bounce…) để progress không tuyến tính — chuyển động tự nhiên hơn.",
  "CurvedAnimation provide animation curve behavior.",
  {"A":"Layout ≠ animation curve.","C":"State updates là setState/BLoC.","D":"Navigation là router."},
  "Curve = nhịp animation không linear."),

Q("SP26-FE", 11,
  "How can data be passed to a new screen?",
  {"A":"Using global variables","B":"Via constructor arguments","C":"Using ThemeData","D":"Using Scaffold"},
  "B",
  "Làm sao truyền dữ liệu sang màn hình mới?",
  {"A":"Dùng biến global","B":"Qua tham số constructor","C":"Dùng ThemeData","D":"Dùng Scaffold"},
  "Cách idiomatic: Navigator.push MaterialPageRoute(builder: (_) => DetailPage(item: x)) — truyền qua constructor/route settings.",
  "Pass data to new screen primarily via constructor arguments (hoặc arguments của route).",
  {"A":"Global biến là anti-pattern, khó test.","C":"ThemeData là style.","D":"Scaffold là khung màn hình."},
  "Màn mới nhận data qua constructor."),

Q("SP26-FE", 12,
  "What is the purpose of parsing JSON?",
  {"A":"Encrypt data","B":"Convert JSON into Dart objects","C":"Send requests","D":"Cache responses"},
  "B",
  "Mục đích của parsing JSON là gì?",
  {"A":"Mã hóa data","B":"Chuyển JSON thành object Dart","C":"Gửi request","D":"Cache response"},
  "API trả JSON string/map → parse (jsonDecode + fromJson) thành model class để type-safe trong app.",
  "Parsing JSON = convert JSON into Dart objects.",
  {"A":"Encrypt là cryptography.","C":"Send request là HTTP client.","D":"Cache là lưu trữ tạm."},
  "JSON → Model Dart = parse."),

Q("SP26-FE", 13,
  "Which phase involves gathering requirements?",
  {"A":"Implementation","B":"Design","C":"Analysis","D":"Testing"},
  "C",
  "Giai đoạn nào bao gồm thu thập yêu cầu?",
  {"A":"Implementation","B":"Design","C":"Analysis","D":"Testing"},
  "Vòng đời phần mềm: Analysis/requirements → Design → Implementation → Testing → Deploy. Analysis làm rõ “cần gì”.",
  "Gathering requirements thuộc Analysis phase.",
  {"A":"Implementation = viết code.","B":"Design = thiết kế giải pháp.","D":"Testing = kiểm thử."},
  "Requirements → Analysis."),

Q("SP26-FE", 14,
  "Which Flutter tool helps debug network requests?",
  {"A":"DevTools","B":"Inspector","C":"Emulator","D":"Hot reload"},
  "A",
  "Công cụ Flutter nào giúp debug network requests?",
  {"A":"DevTools","B":"Inspector","C":"Emulator","D":"Hot reload"},
  "Flutter DevTools có Network view (và logging) để xem request/response khi debug app.",
  "Debug network → DevTools.",
  {"B":"Inspector tập trung widget tree/layout.","C":"Emulator chỉ runtime environment.","D":"Hot reload nạp lại UI code."},
  "Xem API call → DevTools Network."),

Q("SP26-FE", 15,
  "Which Dart feature supports object-oriented programming?",
  {"A":"Widgets","B":"Classes and objects","C":"Hot reload","D":"Layout builders"},
  "B",
  "Tính năng Dart nào hỗ trợ lập trình hướng đối tượng?",
  {"A":"Widgets","B":"Classes và objects","C":"Hot reload","D":"Layout builders"},
  "OOP pillars trong Dart: class, object, inheritance, mixin, interface, encapsulation.",
  "Classes and objects là nền OOP của Dart.",
  {"A":"Widget dùng OOP nhưng là Flutter UI, không định nghĩa OOP language.","C":"Hot reload là tooling.","D":"LayoutBuilder là widget layout."},
  "OOP Dart = class & object."),

Q("SP26-FE", 16,
  "Which approach helps reduce unnecessary widget rebuilds?",
  {"A":"Using global variables","B":"Fine-grained state updates","C":"Hot restart","D":"Large widgets"},
  "B",
  "Cách tiếp cận nào giúp giảm rebuild widget không cần thiết?",
  {"A":"Dùng biến global","B":"Cập nhật state mịn (fine-grained)","C":"Hot restart","D":"Widget lớn"},
  "Fine-grained: chỉ notify listener/widget quan tâm (Selector, BlocSelector, tách state nhỏ) thay vì setState cả page.",
  "Fine-grained state updates giảm unnecessary rebuilds.",
  {"A":"Global dễ rebuild lung tung.","C":"Hot restart là dev tool.","D":"Large widgets làm rebuild đắt hơn."},
  "State mịn = rebuild ít."),

Q("SP26-FE", 17,
  "Which action best demonstrates Flutter's reactive UI model?",
  {"A":"Manually updating UI elements","B":"Rebuilding UI in response to state changes","C":"Editing layout XML","D":"Calling native APIs"},
  "B",
  "Hành động nào thể hiện rõ nhất mô hình UI reactive của Flutter?",
  {"A":"Cập nhật UI thủ công từng element","B":"Rebuild UI khi state đổi","C":"Sửa layout XML","D":"Gọi native API"},
  "Reactive/declarative: UI = f(state). State đổi → rebuild mô tả UI mới. Không findViewById rồi setText kiểu imperative cổ điển.",
  "Reactive model = rebuilding UI in response to state changes.",
  {"A":"Manual update là imperative, không đặc trưng Flutter.","C":"Không dùng XML layout.","D":"Native API là platform channel, không định nghĩa reactive UI."},
  "State → UI rebuild = reactive."),

Q("SP26-FE", 18,
  "Why are const widgets recommended?",
  {"A":"They improve readability","B":"They reduce rebuild cost","C":"They add state","D":"They handle navigation"},
  "B",
  "Vì sao nên dùng const widgets?",
  {"A":"Dễ đọc hơn","B":"Giảm chi phí rebuild","C":"Thêm state","D":"Xử lý navigation"},
  "const widget tạo compile-time constant; framework có thể tái sử dụng instance, bỏ qua rebuild nếu identical — performance win.",
  "const widgets reduce rebuild cost.",
  {"A":"Readability là phụ.","C":"const widget immutable, không add state.","D":"Không liên quan navigation."},
  "const Text(...) khi có thể."),

Q("SP26-FE", 19,
  "Why should animations be disposed properly?",
  {"A":"Improve UI","B":"Prevent memory leaks","C":"Speed up builds","D":"Fix layout"},
  "B",
  "Vì sao phải dispose animation đúng cách?",
  {"A":"UI đẹp hơn","B":"Tránh rò rỉ bộ nhớ","C":"Build nhanh hơn","D":"Sửa layout"},
  "AnimationController gắn Ticker; không dispose → ticker chạy ngầm, leak memory/CPU, assert trong debug.",
  "Dispose animation để prevent memory leaks.",
  {"A":"Không phải lý do chính.","C":"Không ảnh hưởng compile build.","D":"Không fix layout."},
  "Controller animation → luôn dispose."),

Q("SP26-FE", 20,
  "Which Flutter test focuses on UI components?",
  {"A":"Unit test","B":"Widget test","C":"Integration test","D":"Load test"},
  "B",
  "Loại test Flutter nào tập trung vào UI components?",
  {"A":"Unit test","B":"Widget test","C":"Integration test","D":"Load test"},
  "Widget test (flutter_test) bơm widget vào test environment, pump, tap, expect text — không cần full device như integration.",
  "UI components → Widget test.",
  {"A":"Unit = logic thuần.","C":"Integration = end-to-end app.","D":"Load test = hiệu năng tải."},
  "Test UI widget → widget_test."),

Q("SP26-FE", 21,
  "Why should database operations be asynchronous?",
  {"A":"Simplify syntax","B":"Avoid blocking UI thread","C":"Reduce code","D":"Improve theme"},
  "B",
  "Vì sao thao tác database nên bất đồng bộ?",
  {"A":"Cú pháp đơn giản hơn","B":"Tránh chặn UI thread","C":"Giảm code","D":"Cải thiện theme"},
  "I/O DB có thể chậm. Chạy sync trên UI isolate → jank/ANR. Dùng async/await hoặc isolate để UI mượt.",
  "DB async để avoid blocking UI thread.",
  {"A":"Async không hẳn đơn giản hơn.","C":"Không giảm code.","D":"Không liên quan theme."},
  "DB/IO → async, giữ UI mượt."),

Q("SP26-FE", 22,
  "Why is Chapter 13 considered optional (Plus)?",
  {"A":"It replaces core concepts","B":"Apps can work without deep optimization","C":"It manages navigation","D":"It handles authentication"},
  "B",
  "Vì sao Chapter 13 được xem là optional (Plus)?",
  {"A":"Thay thế kiến thức core","B":"App vẫn chạy được mà không cần tối ưu sâu","C":"Quản lý navigation","D":"Xử lý authentication"},
  "Chương Plus về optimization/performance nâng cao: hữu ích production nhưng app demo/core features vẫn chạy thiếu nó.",
  "Optional vì apps can work without deep optimization.",
  {"A":"Không thay core.","C":"Navigation không phải lý do optional ch.13.","D":"Auth thuộc chủ đề khác."},
  "Plus optimize: học sau khi app đã đúng."),

Q("SP26-FE", 23,
  "Which widget applies a theme to an entire Flutter application?",
  {"A":"Scaffold","B":"Theme","C":"MaterialApp","D":"Container"},
  "C",
  "Widget nào áp theme cho toàn bộ ứng dụng Flutter?",
  {"A":"Scaffold","B":"Theme","C":"MaterialApp","D":"Container"},
  "MaterialApp(theme: ThemeData(...)) bọc app, cung cấp Material + theme gốc. Theme widget có thể override cục bộ; Scaffold là khung 1 màn.",
  "Toàn app → MaterialApp (kèm theme:).",
  {"A":"Scaffold = cấu trúc 1 screen.","B":"Theme override subtree, không phải root app điển hình.","D":"Container chỉ box UI."},
  "MaterialApp.theme = skin global."),

Q("SP26-FE", 24,
  "What is the purpose of SliverAppBar?",
  {"A":"Static app bar","B":"Scrollable flexible app bar","C":"Bottom navigation","D":"Drawer control"},
  "B",
  "Mục đích của SliverAppBar là gì?",
  {"A":"App bar tĩnh","B":"App bar linh hoạt theo scroll","C":"Nav dưới","D":"Drawer"},
  "SliverAppBar trong CustomScrollView: expand/collapse theo cuộn — flexibleSpace, pinned, floating.",
  "SliverAppBar = scrollable flexible app bar.",
  {"A":"Không chỉ static AppBar.","C":"Bottom nav khác.","D":"Drawer khác."},
  "Scroll header co giãn → SliverAppBar."),

Q("SP26-FE", 25,
  "Which widget is best used to add fixed empty space?",
  {"A":"Padding","B":"Expanded","C":"SizedBox","D":"Container"},
  "C",
  "Widget nào tốt nhất để thêm khoảng trống cố định?",
  {"A":"Padding","B":"Expanded","C":"SizedBox","D":"Container"},
  "SizedBox(width/height) tạo khoảng/gap cố định rõ ràng, nhẹ. Padding bọc child; Expanded chiếm flex; Container nặng hơn nếu chỉ cần size.",
  "Fixed empty space → SizedBox là best practice phổ biến.",
  {"A":"Padding cho inset quanh child, không phải gap thuần luôn.","B":"Expanded co giãn theo flex, không “fixed”.","D":"Container làm được nhưng overkill."},
  "Gap cố định → SizedBox."),

Q("SP26-FE", 26,
  "Which package supports BLoC architecture?",
  {"A":"provider","B":"flutter_bloc","C":"sqflite","D":"http"},
  "B",
  "Package nào hỗ trợ kiến trúc BLoC?",
  {"A":"provider","B":"flutter_bloc","C":"sqflite","D":"http"},
  "flutter_bloc cung cấp Bloc/Cubit, BlocProvider, BlocBuilder/Listener — implementation chính thức phổ biến của pattern BLoC trên Flutter.",
  "BLoC architecture package → flutter_bloc.",
  {"A":"provider là DI/state khác.","C":"sqflite = DB.","D":"http = network."},
  "BLoC code → package flutter_bloc."),

Q("SP26-FE", 27,
  "Which Flutter widget reacts to authentication state changes?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Form"},
  "B",
  "Widget Flutter nào phản ứng với thay đổi trạng thái authentication?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Form"},
  "Auth state thường là stream liên tục (loggedIn/out). StreamBuilder (hoặc BlocBuilder trên stream state) rebuild UI khi auth đổi. FutureBuilder one-shot.",
  "Auth state changes theo thời gian → StreamBuilder phù hợp nhất trong các lựa chọn.",
  {"A":"FutureBuilder cho Future một lần.","C":"ListView hiển thị list.","D":"Form nhập liệu."},
  "Auth stream → StreamBuilder."),

Q("SP26-FE", 28,
  "What is technical debt?",
  {"A":"UI lag","B":"Future cost of poor design decisions","C":"Memory usage","D":"API limit"},
  "B",
  "Technical debt là gì?",
  {"A":"UI giật","B":"Chi phí tương lai của quyết định thiết kế kém","C":"Mức dùng bộ nhớ","D":"Giới hạn API"},
  "Technical debt: “vay” bằng shortcut/code xấu hôm nay → trả lãi bằng thời gian fix/refactor/bugs sau này.",
  "Technical debt = future cost of poor design decisions.",
  {"A":"UI lag là triệu chứng performance.","C":"Memory là metric runtime.","D":"API limit là quota."},
  "Code tạm bợ hôm nay = nợ kỹ thuật."),

Q("SP26-FE", 29,
  "What is implicit animation?",
  {"A":"Manual animation control","B":"Animation without controller","C":"API animation","D":"Navigation animation"},
  "B",
  "Implicit animation là gì?",
  {"A":"Điều khiển animation thủ công","B":"Animation không cần controller","C":"Animation API backend","D":"Animation điều hướng"},
  "Implicit (AnimatedContainer, AnimatedOpacity…): đổi property + duration, framework tự animate. Explicit: AnimationController + Tween.",
  "Implicit animation = animation without (explicit) controller.",
  {"A":"Manual control = explicit animation.","C":"Không phải API server.","D":"Nav transition là chủ đề riêng (Hero/PageRoute)."},
  "Implicit = Animated* không Controller."),

Q("SP26-FE", 30,
  "Which Dart data structure is best suited for storing an ordered collection of items?",
  {"A":"Set","B":"Map","C":"List","D":"Queue"},
  "C",
  "Cấu trúc dữ liệu Dart nào phù hợp nhất để lưu collection có thứ tự?",
  {"A":"Set","B":"Map","C":"List","D":"Queue"},
  "List giữ thứ tự chèn và index. Set không trùng & không nhấn order dùng thông dụng; Map là key-value; Queue (collection package) ít dùng hơn List trong câu hỏi FE.",
  "Ordered collection phổ biến → List.",
  {"A":"Set: unique, không phải list có index.","B":"Map: key-value.","D":"Queue có order nhưng không phải cấu trúc “mặc định” như List trong Dart core cho use-case chung."},
  "Danh sách có thứ tự → List."),

Q("SP26-FE", 31,
  "Which Flutter concept supports reactive UI updates?",
  {"A":"Manual refresh","B":"Widget rebuilding","C":"Hot restart","D":"Native callbacks"},
  "B",
  "Khái niệm Flutter nào hỗ trợ cập nhật UI reactive?",
  {"A":"Refresh thủ công","B":"Widget rebuilding","C":"Hot restart","D":"Native callbacks"},
  "Reactive UI dựa trên việc rebuild widget khi model/state đổi — declarative UI description cập nhật.",
  "Reactive updates qua widget rebuilding.",
  {"A":"Manual refresh không phải mô hình chính.","C":"Hot restart là dev.","D":"Native callbacks là platform bridge."},
  "Reactive = rebuild theo state."),

Q("SP26-FE", 32,
  "Which type of test checks individual functions or classes?",
  {"A":"Widget test","B":"Integration test","C":"Unit test","D":"System test"},
  "C",
  "Loại test nào kiểm tra từng hàm hoặc class riêng lẻ?",
  {"A":"Widget test","B":"Integration test","C":"Unit test","D":"System test"},
  "Unit test: nhỏ, nhanh, test pure logic (function/class) độc lập UI/device.",
  "Individual functions/classes → Unit test.",
  {"A":"Widget test = UI component.","B":"Integration = e2e.","D":"System test gần e2e toàn hệ thống, không phải unit."},
  "Hàm/class → unit test."),

Q("SP26-FE", 33,
  "What is the role of events in BLoC?",
  {"A":"Store UI","B":"Trigger state changes","C":"Render widgets","D":"Handle layout"},
  "B",
  "Vai trò của events trong BLoC là gì?",
  {"A":"Lưu UI","B":"Kích hoạt thay đổi state","C":"Render widget","D":"Xử lý layout"},
  "Event = tín hiệu từ UI/domain (button pressed, data loaded). BLoC map event → state mới.",
  "Events trigger state changes.",
  {"A":"Không store UI.","C":"Render là widget.build.","D":"Layout là render/layout phase."},
  "Event → BLoC → State."),

Q("SP26-FE", 34,
  "What is the main purpose of hot reload in Flutter?",
  {"A":"Improve runtime performance","B":"Instantly reflect code changes in UI","C":"Publish apps faster","D":"Reduce memory usage"},
  "B",
  "Mục đích chính của hot reload trong Flutter là gì?",
  {"A":"Tăng performance runtime","B":"Phản ánh ngay thay đổi code lên UI","C":"Publish app nhanh hơn","D":"Giảm bộ nhớ"},
  "Hot reload inject updated source vào VM đang chạy, giữ state — dev thấy UI đổi trong giây lát (khác hot restart reset state).",
  "Hot reload instantly reflect code changes in UI khi dev.",
  {"A":"Không tối ưu app user cuối.","C":"Không publish store.","D":"Không giảm memory production."},
  "Sửa code → hot reload → thấy ngay."),

Q("SP26-FE", 35,
  "Why are forms important in mobile applications?",
  {"A":"UI decoration","B":"User data collection","C":"State management","D":"Navigation"},
  "B",
  "Vì sao form quan trọng trong mobile app?",
  {"A":"Trang trí UI","B":"Thu thập dữ liệu người dùng","C":"Quản lý state","D":"Điều hướng"},
  "Form (login, đăng ký, checkout): nhập + validate + submit dữ liệu user — luồng business cốt lõi nhiều app.",
  "Forms for user data collection.",
  {"A":"Không chỉ decoration.","C":"State management là cơ chế rộng hơn.","D":"Navigation khác form."},
  "Form = thu thập input user."),

Q("SP26-FE", 36,
  "Which method retrieves data from SharedPreferences?",
  {"A":"get()","B":"read()","C":"fetch()","D":"load()"},
  "A",
  "Method nào lấy dữ liệu từ SharedPreferences?",
  {"A":"get()","B":"read()","C":"fetch()","D":"load()"},
  "API shared_preferences: getString/getInt/getBool… (họ get*). Không có read/fetch/load chuẩn như tên đó trên prefs API.",
  "Retrieve prefs → get… (get()).",
  {"B":"read() không phải API chuẩn SharedPreferences Flutter.","C":"fetch() gợi HTTP.","D":"load() không phải method prefs phổ biến."},
  "prefs.getString('key')."),

Q("SP26-FE", 37,
  "What is the main benefit of Flutter's widget-based architecture?",
  {"A":"Widgets are only used for layout design","B":"Widgets allow code reuse across platforms","C":"Widgets automatically manage databases","D":"Widgets replace backend services"},
  "B",
  "Lợi ích chính của kiến trúc dựa trên widget của Flutter là gì?",
  {"A":"Widget chỉ dùng cho layout","B":"Widget cho phép tái sử dụng code đa nền tảng","C":"Widget tự quản lý database","D":"Widget thay backend"},
  "Everything is a widget + same widget tree compile ra nhiều platform → reuse UI code Android/iOS/web/desktop.",
  "Main benefit: widgets allow code reuse across platforms.",
  {"A":"Widget còn semantics, paint, input… không chỉ layout.","C":"DB không do widget quản.","D":"Backend vẫn cần server."},
  "Widget = UI tái sử dụng đa platform."),

Q("SP26-FE", 38,
  "Why are widgets lightweight in Flutter?",
  {"A":"They manage system resources","B":"They are immutable descriptions","C":"They store UI state","D":"They handle rendering directly"},
  "B",
  "Vì sao widget trong Flutter được coi là lightweight?",
  {"A":"Chúng quản lý tài nguyên hệ thống","B":"Chúng là mô tả bất biến (immutable)","C":"Chúng lưu state UI","D":"Chúng render trực tiếp"},
  "Widget là cấu hình immutable rẻ để tạo; Element/RenderObject mới giữ state/layout/paint bền hơn. Rebuild widget tree tương đối rẻ.",
  "Widgets lightweight vì they are immutable descriptions of UI, không phải heavy view objects.",
  {"A":"Resource nặng thuộc engine/render objects.","C":"State lâu dài ở State/Element, không phải Stateless widget.","D":"Render do RenderObject/Engine."},
  "Widget = mô tả nhẹ, immutable."),

Q("SP26-FE", 39,
  "Why should authentication state be centralized?",
  {"A":"Reduce UI code","B":"Ensure consistent access control","C":"Improve animations","D":"Simplify layout"},
  "B",
  "Vì sao nên tập trung (centralize) authentication state?",
  {"A":"Giảm code UI","B":"Đảm bảo kiểm soát truy cập nhất quán","C":"Cải thiện animation","D":"Đơn giản layout"},
  "Một nguồn auth truth (BLoC/Provider): mọi màn/guard đọc cùng state → tránh màn A tưởng logged-in, màn B tưởng logged-out.",
  "Centralize auth → consistent access control.",
  {"A":"Không phải mục tiêu chính.","C":"Không liên quan animation.","D":"Không liên quan layout."},
  "Auth một chỗ = phân quyền đồng nhất."),

Q("SP26-FE", 40,
  "Which widget can hide user input text when configured for password entry?",
  {"A":"TextField","B":"ObscureText","C":"SecureInput","D":"PasswordField"},
  "A",
  "Widget nào có thể ẩn chữ người dùng nhập khi cấu hình cho mật khẩu?",
  {"A":"TextField","B":"ObscureText","C":"SecureInput","D":"PasswordField"},
  "TextField(obscureText: true) ẩn ký tự password. obscureText là property, không phải widget; SecureInput/PasswordField không phải widget Material chuẩn.",
  "Password masking: TextField với obscureText: true.",
  {"B":"obscureText là tham số bool, không phải widget.","C":"SecureInput không phải widget Flutter chuẩn.","D":"PasswordField không phải Material widget built-in phổ biến."},
  "TextField + obscureText: true."),

Q("SP26-FE", 41,
  "What is Flutter primarily used for?",
  {"A":"Designing databases for mobile apps","B":"Creating native applications from a single codebase","C":"Developing server-side applications only","D":"Building operating systems for mobile devices"},
  "B",
  "Flutter chủ yếu dùng để làm gì?",
  {"A":"Thiết kế database mobile","B":"Tạo ứng dụng native từ một codebase","C":"Chỉ dev server-side","D":"Xây hệ điều hành mobile"},
  "Flutter = UI toolkit cross-platform compile/run gần native performance từ một codebase Dart.",
  "Primarily: creating native applications from a single codebase.",
  {"A":"Không phải DB designer.","C":"Không chỉ server-side.","D":"Không làm OS."},
  "Flutter = multi-platform apps, 1 codebase."),

Q("SP26-FE", 42,
  "Which method resets all form fields?",
  {"A":"clear()","B":"reset()","C":"dispose()","D":"remove()"},
  "B",
  "Method nào reset toàn bộ các field của form?",
  {"A":"clear()","B":"reset()","C":"dispose()","D":"remove()"},
  "FormState.reset() đưa fields về initialValue và reset validation. controller.clear() chỉ xóa text từng field; dispose hủy resource.",
  "Reset all form fields → FormState.reset().",
  {"A":"clear() thường trên TextEditingController từng ô.","C":"dispose() dọn controller/state, không “reset form”.","D":"remove() không phải API form chuẩn."},
  "formKey.currentState?.reset()."),

Q("SP26-FE", 43,
  "Which Dart keyword is used to define a constant value at compile time?",
  {"A":"final","B":"static","C":"const","D":"var"},
  "C",
  "Keyword Dart nào định nghĩa hằng số tại compile time?",
  {"A":"final","B":"static","C":"const","D":"var"},
  "const = compile-time constant. final = gán 1 lần runtime. static = thành viên class. var = suy luận kiểu.",
  "Compile-time constant → const.",
  {"A":"final có thể runtime init một lần.","B":"static không có nghĩa hằng compile-time.","D":"var biến mutable (trừ khi final var)."},
  "const = biết từ lúc compile."),

Q("SP26-FE", 44,
  "What happens after successful login?",
  {"A":"App closes","B":"User session starts","C":"Theme changes","D":"Navigation resets"},
  "B",
  "Điều gì xảy ra sau khi đăng nhập thành công?",
  {"A":"App đóng","B":"Phiên người dùng bắt đầu","C":"Theme đổi","D":"Navigation reset"},
  "Login thành công → tạo session (lưu token/user), đánh dấu authenticated, cho phép vào vùng protected.",
  "After successful login: user session starts.",
  {"A":"App không đóng.","C":"Theme không buộc đổi.","D":"Có thể navigate nhưng “session starts” mới là bản chất auth."},
  "Login OK → session + token."),

Q("SP26-FE", 45,
  "Which step is required before running a Flutter app for the first time?",
  {"A":"Publishing the app","B":"Setting up the Flutter SDK","C":"Configuring a database","D":"Writing backend APIs"},
  "B",
  "Bước nào bắt buộc trước khi chạy Flutter app lần đầu?",
  {"A":"Publish app","B":"Cài đặt Flutter SDK","C":"Cấu hình database","D":"Viết backend API"},
  "Cần Flutter SDK + toolchain (Android SDK/Xcode…) rồi mới flutter run. DB/API/publish không bắt buộc cho hello-world.",
  "First run requires setting up the Flutter SDK.",
  {"A":"Publish sau khi hoàn thiện.","C":"DB tùy app.","D":"Backend tùy app."},
  "Cài Flutter SDK trước đã."),

Q("SP26-FE", 46,
  "Which widget reacts to async data from local storage?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Provider"},
  "A",
  "Widget nào phản ứng với dữ liệu async từ local storage?",
  {"A":"FutureBuilder","B":"StreamBuilder","C":"ListView","D":"Provider"},
  "Local storage read (SharedPreferences) trả Future → FutureBuilder. StreamBuilder cho stream liên tục.",
  "Async local storage one-shot → FutureBuilder.",
  {"B":"StreamBuilder cho Stream.","C":"ListView chỉ list.","D":"Provider không tự bind Future storage."},
  "prefs Future → FutureBuilder."),

Q("SP26-FE", 47,
  "What does golden testing verify?",
  {"A":"API responses","B":"UI appearance consistency","C":"Database state","D":"Authentication"},
  "B",
  "Golden testing kiểm tra điều gì?",
  {"A":"Phản hồi API","B":"Tính nhất quán giao diện UI","C":"Trạng thái database","D":"Authentication"},
  "Golden (screenshot) test so sánh UI render với ảnh chuẩn — phát hiện lệch pixel/layout ngoài ý muốn.",
  "Golden testing verifies UI appearance consistency.",
  {"A":"API là unit/integration network tests.","C":"DB state là data tests.","D":"Auth là security/flow tests."},
  "Golden = chụp UI chuẩn để so."),

Q("SP26-FE", 48,
  "Why should state be kept as local as possible?",
  {"A":"Better animations","B":"Reduce unnecessary rebuilds","C":"Simplify UI","D":"Improve navigation"},
  "B",
  "Vì sao nên giữ state càng local càng tốt?",
  {"A":"Animation tốt hơn","B":"Giảm rebuild không cần thiết","C":"Đơn giản UI","D":"Cải thiện navigation"},
  "State nâng cao cây widget → nhiều subtree rebuild. Local state chỉ đụng widget cần → hiệu năng & rõ ownership.",
  "Local state reduces unnecessary rebuilds.",
  {"A":"Không trực tiếp vì animation.","C":"Có thể code đơn giản hơn nhưng lý do chính là rebuild scope.","D":"Navigation không phải lý do chính."},
  "State thấp nhất có thể → rebuild hẹp."),

Q("SP26-FE", 49,
  "What is the benefit of composing widgets in Flutter?",
  {"A":"Faster compilation","B":"Better code reuse and UI consistency","C":"Reduced memory usage","D":"Automatic navigation"},
  "B",
  "Lợi ích của việc composition (ghép) widgets trong Flutter là gì?",
  {"A":"Compile nhanh hơn","B":"Tái sử dụng code và UI nhất quán hơn","C":"Giảm bộ nhớ","D":"Tự động navigation"},
  "Composition over inheritance: ghép widget nhỏ (Button styles, cards) → reuse, consistent design system.",
  "Composing widgets → better code reuse and UI consistency.",
  {"A":"Không đảm bảo compile nhanh.","C":"Không hẳn giảm memory.","D":"Không auto navigation."},
  "Widget nhỏ ghép lại = tái sử dụng."),

Q("SP26-FE", 50,
  "Which status code indicates server error?",
  {"A":"200","B":"301","C":"404","D":"500"},
  "D",
  "Mã status nào cho biết lỗi phía server?",
  {"A":"200","B":"301","C":"404","D":"500"},
  "HTTP: 2xx success, 3xx redirect, 4xx client error (404 not found), 5xx server error (500 Internal Server Error).",
  "Server error class → 500 (5xx).",
  {"A":"200 OK = thành công.","B":"301 = redirect vĩnh viễn.","C":"404 = client: không tìm thấy resource."},
  "5xx = lỗi server; 500 điển hình."),
]
# fmt: on


def main() -> None:
    items = B5 + FE
    for i, q in enumerate(items, start=1):
        q["id"] = i

    # de-dup check
    keys = [(q["source"], q["num"]) for q in items]
    assert len(keys) == len(set(keys)), "duplicate source/num"

    json_path = OUT_DIR / "questions.json"
    js_path = OUT_DIR / "questions.js"
    json_path.write_text(
        json.dumps(items, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    js_path.write_text(
        "window.QUIZ_QUESTIONS = "
        + json.dumps(items, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )

    # human-readable data.txt style
    lines: list[str] = [
        "PRM393 Quiz Data — SP26 B5 FE (48) + SP26 FE (50) = 98 câu",
        "Mỗi câu: EN + VI + đáp án + khái niệm + giải thích",
        "",
    ]
    for q in items:
        exp = q["explanation"]
        lines.append(f"===== [{q['id']}] {q['examLabel']} #{q['num']} =====")
        lines.append(q["question"])
        lines.append(f"(VI) {exp['questionVi']}")
        for L, t in q["options"].items():
            mark = " ✓" if L == q["answer"] else ""
            lines.append(f"  {L}. {t}{mark}")
            lines.append(f"     VI: {exp['optionsVi'].get(L, '')}")
        lines.append(f"Đáp án: {exp['answerDisplay']}")
        lines.append(exp["whyCorrect"])
        lines.append(f"Mẹo: {exp['memoryTip']}")
        for L, w in exp["whyWrong"].items():
            lines.append(f"  Sai {L}: {w}")
        lines.append("")

    (OUT_DIR / "quiz_data.txt").write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {len(items)} questions")
    print(f"  {json_path}")
    print(f"  {js_path}")
    print(f"  {OUT_DIR / 'quiz_data.txt'}")
    print(f"  B5={sum(1 for q in items if q['source']=='SP26-B5-FE')} FE={sum(1 for q in items if q['source']=='SP26-FE')}")


if __name__ == "__main__":
    main()
