/**
 * Short bank300 stems → dense Vietnamese (exact keys = actual bank text).
 */
export const FE_BANK300_Q = [
  ["Hexadecimal digit A in decimal?", "Chữ số hex A bằng bao nhiêu thập phân?"],
  ["Range of n-bit 2's complement?", "Phạm vi số bù 2 n-bit?"],
  ["RAID 1 main feature?", "Đặc trưng chính của RAID 1?"],
  ["RAID 0 main feature?", "Đặc trưng chính của RAID 0?"],
  ["PC register holds?", "Thanh ghi PC (program counter) giữ gì?"],
  ["Pipeline hazard types?", "Các loại hazard trong pipeline?"],
  ["Airline reservation immediate response?", "Đặt vé máy bay cần phản hồi ngay — kiểu xử lý nào?"],
  ["Round Robin reduces?", "Round Robin chủ yếu giảm gì?"],
  ["Coffman conditions count?", "Số điều kiện Coffman (deadlock)?"],
  ["Kernel modes?", "Các mode của kernel?"],
  ["Microkernel vs monolithic?", "Microkernel khác monolithic thế nào?"],
  ["Thrashing?", "Thrashing là gì?"],
  ["Backup types?", "Các loại backup?"],
  ["Selection relational op?", "Phép Selection trong quan hệ làm gì?"],
  ["Projection relational op?", "Phép Projection trong quan hệ làm gì?"],
  ["JOIN does?", "JOIN làm gì?"],
  ["DNS role?", "Vai trò của DNS?"],
  ["DHCP role?", "Vai trò của DHCP?"],
  ["TCP vs UDP?", "TCP khác UDP thế nào?"],
  ["HTTP port commonly?", "Cổng HTTP thường dùng?"],
  ["CDMA/CDM idea?", "Ý tưởng CDMA/CDM?"],
  ["CCU role?", "Vai trò của CCU?"],
  ["Modem role?", "Vai trò của modem?"],
  ["Switch vs hub?", "Switch khác hub thế nào?"],
  ["Router works at?", "Router hoạt động ở tầng nào?"],
  ["IPv4 bits?", "IPv4 có bao nhiêu bit?"],
  ["IPv6 bits?", "IPv6 có bao nhiêu bit?"],
  ["ISMS Act phase?", "Pha Act trong ISMS (PDCA) làm gì?"],
  ["Risk assessment proper approach?", "Cách tiếp cận đánh giá rủi ro phù hợp?"],
  ["WPA is?", "WPA là gì?"],
  ["WAF is?", "WAF là gì?"],
  ["Reverse proxy does?", "Reverse proxy làm gì?"],
  ["Forward proxy does?", "Forward proxy làm gì?"],
  ["OP25B is?", "OP25B là gì?"],
  ["JPCERT/CC role?", "Vai trò JPCERT/CC?"],
  ["Symmetric crypto other name?", "Mật mã đối xứng còn gọi là?"],
  ["Hash property?", "Tính chất chính của hash?"],
  ["FIFO structure?", "Cấu trúc FIFO?"],
  ["LIFO structure?", "Cấu trúc LIFO?"],
  ["RPN of (A+B)*(C-D/E)?", "RPN (hậu tố) của (A+B)*(C-D/E)?"],
  ["Bubble sort idea?", "Ý tưởng bubble sort?"],
  ["Selection sort first pass on 84 73 28 16 51?", "Selection sort lượt 1 trên 84 73 28 16 51?"],
  ["Linear search worst complexity?", "Độ phức tạp tệ nhất linear search?"],
  ["Binary search complexity?", "Độ phức tạp binary search?"],
  ["Linked list insert advantage?", "Ưu điểm chèn linked list?"],
  ["Hash average search?", "Tìm kiếm trung bình trên hash?"],
  ["Merge sort complexity?", "Độ phức tạp merge sort?"],
  ["Quicksort worst case?", "Quicksort trường hợp xấu nhất?"],
  ["PDCA letters?", "PDCA viết tắt các chữ?"],
  ["Assets = ?", "Assets = ? (phương trình kế toán)"],
  ["Break-even idea?", "Ý tưởng điểm hòa vốn?"],
  ["QC Pareto idea?", "Ý tưởng biểu đồ Pareto QC?"],
  ["Ishikawa diagram?", "Biểu đồ Ishikawa (xương cá) là gì?"],
  ["Competitive leader strategy?", "Chiến lược competitive leader?"],
  ["Nicher strategy?", "Chiến lược nicher?"],
  ["4P marketing?", "4P marketing gồm?"],
  ["CIO approves?", "CIO phê duyệt gì?"],
  ["ITIL de facto for?", "ITIL là chuẩn de facto cho?"],
  ["SLA is?", "SLA là gì?"],
  ["Incident vs Problem?", "Incident khác Problem thế nào?"],
  ["Service desk is?", "Service desk là gì?"],
  ["ISO 20000 about?", "ISO 20000 về?"],
  ["Waterfall model?", "Mô hình Waterfall?"],
  ["V-model links?", "V-model liên kết gì?"],
  ["Unit test tests?", "Unit test kiểm thử gì?"],
  ["Black-box testing?", "Kiểm thử black-box?"],
  ["White-box testing?", "Kiểm thử white-box?"],
  ["High cohesion good?", "High cohesion tốt vì?"],
  ["Low coupling good?", "Low coupling tốt vì?"],
  ["Configuration baseline?", "Configuration baseline là gì?"],
  ["WBS is?", "WBS là gì?"],
  ["SPI = ?", "SPI = ?"],
  ["CPI = ?", "CPI = ?"],
  ["Risk responses?", "Các phản ứng rủi ro?"],
  ["IT governance aims?", "IT governance nhằm?"],
  ["COBIT is?", "COBIT là gì?"],
  ["B2C e-business?", "B2C e-business?"],
  ["Benchmarking?", "Benchmarking là gì?"],
  ["Outsourcing offshore risk?", "Rủi ro outsourcing offshore?"],
  ["Copyright protects?", "Bản quyền (copyright) bảo vệ?"],
  ["Patent protects?", "Bằng sáng chế (patent) bảo vệ?"],
  ["Going concern?", "Nguyên tắc going concern?"],
  ["Disclosure/IR?", "Disclosure / IR?"],
  ["Green IT?", "Green IT?"],
  ["MBO?", "MBO (Management by Objectives)?"],
  ["Walk-through review?", "Walk-through review?"],
  ["Inspection review?", "Inspection review?"],
  ["Verification vs Validation?", "Verification khác Validation?"],
  ["Stakeholder is?", "Stakeholder là gì?"],
  ["PMO role?", "Vai trò PMO?"],
  ["Matrix organization?", "Tổ chức ma trận?"],
  ["Crashing a schedule?", "Crashing lịch?"],
  ["Fast-tracking?", "Fast-tracking?"],
  ["CMDB?", "CMDB là gì?"],
  ["External audit vs internal?", "Audit ngoài khác audit nội bộ?"],
  ["General IT controls vs application controls?", "General IT controls khác application controls?"],
  ["Series 0.99 * 0.99?", "Độ tin cậy nối tiếp 0.99 × 0.99?"],
  ["Parallel two 0.9 modules approx R?", "Song song hai module 0.9 — R xấp xỉ?"],
  ["2^10 equals?", "2^10 bằng?"],
  ["2^8 equals?", "2^8 bằng?"],
  ["16-bit patterns count?", "Số mẫu bit 16-bit?"],
  ["Hex F decimal?", "Hex F thập phân?"],
  ["Hex 10 decimal?", "Hex 10 thập phân?"],
  ["Binary 1010 decimal?", "Nhị phân 1010 thập phân?"],
  ["Starvation risk algorithm?", "Thuật toán dễ starvation?"],
  ["Mail receive protocols?", "Giao thức nhận mail?"],
  ["SQL injection defense?", "Phòng SQL injection?"],
  ["IDS vs IPS?", "IDS khác IPS?"],
  ["Soft real-time miss deadline?", "Soft real-time khi trễ deadline?"],
  ["Client-server model?", "Mô hình client–server?"],
  ["3-tier layers?", "Các tầng 3-tier?"],
  ["E-R entity drawn as?", "Thực thể E-R vẽ dạng?"],
  ["Relationship cardinality M:N?", "Bản số quan hệ M:N?"],
  ["COMMIT does?", "COMMIT làm gì?"],
  ["ROLLBACK does?", "ROLLBACK làm gì?"],
  ["View in DB?", "View trong CSDL?"],
  ["GRANT/REVOKE?", "GRANT/REVOKE?"],
  ["Bus topology weakness?", "Nhược điểm topology bus?"],
  ["Optical fiber advantage?", "Ưu điểm cáp quang?"],
  ["Twisted pair common use?", "Cặp xoắn thường dùng?"],
  ["ARP resolves?", "ARP phân giải gì?"],
  ["Requirements: functional vs non-functional?", "Yêu cầu chức năng khác phi chức năng?"],
  ["Queue empty ENQ1 ENQ2 DEQ front?", "Hàng đợi rỗng ENQ1 ENQ2 DEQ — front?"],
  ["Stack empty PUSH1 PUSH2 POP result top?", "Stack rỗng PUSH1 PUSH2 POP — top?"],
  ["Language closest machine with mnemonics?", "Ngôn ngữ gần máy, dùng mnemonic?"],
  ["Combines object modules into executable?", "Ghép object module thành executable?"],
  ["ISMS Plan phase includes?", "Pha Plan của ISMS gồm?"],
  ["Divide and Conquer sort example?", "Ví dụ sort chia để trị?"],
  ["Protocol for secure web?", "Giao thức web an toàn?"],
  ["RAID with parity single disk?", "RAID parity một đĩa?"],
  ["Information amount with n bits?", "Lượng thông tin với n bit?"],
  ["Why user-friendly UI?", "Vì sao UI thân thiện?"],
  ["OSI layer for end-to-end reliability?", "Tầng OSI tin cậy end-to-end?"],
  ["Register is inside CPU: peripheral?", "Thanh ghi trong CPU — ngoại vi?"],
  ["Scheduling that may starve long jobs?", "Lịch có thể starve job dài?"],
  ["Eliminate which condition to prevent deadlock (general)?", "Bỏ điều kiện nào để ngăn deadlock?"],
  ["Cache usually implemented with?", "Cache thường cài bằng?"],
  ["Pipeline hazard types?", "Các loại hazard pipeline?"],
  ["Loads program into memory?", "Nạp chương trình vào bộ nhớ?"],
  ["HTTP port commonly?", "Cổng HTTP thường?"],
  ["ISMS Act phase?", "Pha Act ISMS?"],
  ["Best recursion call handling?", "Cấu trúc tốt nhất cho gọi đệ quy?"],
  ["Singly list traverse from?", "Duyệt danh sách đơn từ?"],
  ["IT service continuity related to?", "IT service continuity liên quan?"],
  ["E-R entity drawn as?", "Thực thể E-R vẽ?"],
  ["Relationship cardinality M:N?", "Bản số M:N?"],
  ["ITIL de facto for?", "ITIL de facto cho?"],
  ["Free use without fee legally for OSS category?", "Dùng miễn phí hợp pháp — nhóm OSS?"],
  ["Admin action forgotten password after verify?", "Admin khi user quên MK (đã verify)?"],
  ["Stack: PUSH3 PUSH7 POP PUSH5 PUSH9 POP top?", "Stack PUSH3 PUSH7 POP PUSH5 PUSH9 POP — top?"],
  ["Queue: ENQA ENQB DEQ ENQC ENQD DEQ front?", "Queue ENQA ENQB DEQ ENQC ENQD DEQ — front?"],
  ["Best OS for many short interactive jobs fairness?", "OS cho nhiều job tương tác ngắn, công bằng?"],
  ["Clean desk policy is which measure type?", "Clean desk thuộc loại biện pháp?"],
  ["How many bits one byte?", "Một byte có bao nhiêu bit?"],
  ["Advantage of semiconductor memory vs magnetic disk?", "Ưu điểm bộ nhớ bán dẫn so đĩa từ?"],
  ["OSI layer frames/MAC?", "Tầng OSI khung/MAC?"],
  // books short stems (residual Đề:)
  ["A common risk of outsourcing is:", "Rủi ro thường gặp của outsourcing là:"],
  ["Unit testing focuses on:", "Unit testing tập trung vào:"],
  ["Agile development emphasizes:", "Phát triển Agile nhấn mạnh:"],
  ["A Gantt chart mainly shows:", "Biểu đồ Gantt chủ yếu thể hiện:"],
  ["Segregation of duties helps to:", "Phân tách nhiệm vụ giúp:"],
  ["An audit trail is useful because it:", "Audit trail hữu ích vì:"],
  ["ER diagrams model:", "Sơ đồ ER mô hình hóa:"],
  ["A deadlock occurs when:", "Deadlock xảy ra khi:"],
  ["HTTPS is essentially:", "HTTPS về bản chất là:"],
  ["A view in SQL is:", "View trong SQL là:"],
  ["A JOIN operation:", "Phép JOIN:"],
  ["COMMIT in a transaction:", "COMMIT trong transaction:"],
  ["UDP is characterized as:", "UDP đặc trưng là:"],
  ["IPv6 addresses are:", "Địa chỉ IPv6:"],
  ["PKI relies on:", "PKI dựa trên:"],
  ["A vulnerability is:", "Lỗ hổng (vulnerability) là:"],
  ["A linked list is characterized by:", "Danh sách liên kết đặc trưng bởi:"],
  ["A graph G=(V,E) consists of:", "Đồ thị G=(V,E) gồm:"],
  ["A trademark protects:", "Nhãn hiệu (trademark) bảo vệ:"],
  ["SOA emphasizes:", "SOA nhấn mạnh:"],
  ["BCP/DR planning aims to:", "Lập kế hoạch BCP/DR nhằm:"],
  ["Requirements definition aims to:", "Định nghĩa yêu cầu nhằm:"],
  ["Integration testing verifies:", "Integration testing kiểm chứng:"],
  ["Cohesion within a module should generally be:", "Cohesion trong module nhìn chung nên:"],
  ["A milestone is:", "Milestone là:"],
  ["A RACI matrix clarifies:", "Ma trận RACI làm rõ:"],
  ["Lessons learned are captured to:", "Lessons learned được ghi nhận để:"],
  ["Evidence in audits should be:", "Bằng chứng audit nên:"],
  ["Preventive controls aim to:", "Kiểm soát phòng ngừa nhằm:"],
  ["Detective controls aim to:", "Kiểm soát phát hiện nhằm:"],
  ["Corrective controls aim to:", "Kiểm soát khắc phục nhằm:"],
];
