import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const quizDir = path.resolve(__dirname, '..');

const subject = process.argv[2] || 'ite';
const metaPath = path.join(quizDir, 'data', subject, '_meta.json');

if (!fs.existsSync(metaPath)) {
  console.error(`Meta file not found: ${metaPath}`);
  process.exit(1);
}

const meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
let allQuestions = [];

for (const taskName of meta.tasks) {
  const taskFile = path.join(quizDir, 'data', subject, `${taskName}.json`);
  if (fs.existsSync(taskFile)) {
    const taskData = JSON.parse(fs.readFileSync(taskFile, 'utf8'));
    if (Array.isArray(taskData.questions)) {
      allQuestions.push(...taskData.questions);
    }
  } else {
    console.warn(`Task file not found: ${taskFile}`);
  }
}

console.log(`Merged ${allQuestions.length} questions for subject '${subject}'`);

const targetJson = path.join(quizDir, 'data', `${subject}.json`);
const targetJs = path.join(quizDir, 'data', `${subject}.js`);

fs.writeFileSync(targetJson, JSON.stringify(allQuestions, null, 2), 'utf8');

const jsContent = `// Auto-generated by merge_by_task — edit quiz/data/${subject}/{task}.json then merge
window.QUIZ_DATA = window.QUIZ_DATA || {};
window.QUIZ_DATA['${subject}'] = ${JSON.stringify(allQuestions, null, 2)};
`;

fs.writeFileSync(targetJs, jsContent, 'utf8');
console.log(`Successfully updated ${targetJson} and ${targetJs}`);
