import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const mlnJsonPath = path.join(ROOT, 'data', 'mln.json');
const mlnJsPath = path.join(ROOT, 'data', 'mln.js');

const mlnData = JSON.parse(fs.readFileSync(mlnJsonPath, 'utf8'));
const qs = mlnData.questions || mlnData;

const jsContent = `// Auto-generated by quiz/tools/rebuild_mln_js.mjs\n` +
  `window.QUIZ_DATA = window.QUIZ_DATA || {};\n` +
  `window.QUIZ_DATA["mln"] = ${JSON.stringify(qs)};\n`;

fs.writeFileSync(mlnJsPath, jsContent, 'utf8');

console.log(`[ok] Updated quiz/data/mln.js with ${qs.length} questions.`);
