import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const mlnJsPath = path.resolve(__dirname, '../data/mln.js');

const content = fs.readFileSync(mlnJsPath, 'utf8');
const jsonStr = content.replace('// Auto-generated by quiz/tools/rebuild_mln_js.mjs\nwindow.QUIZ_DATA = window.QUIZ_DATA || {};\nwindow.QUIZ_DATA["mln"] = ', '').replace(/;\s*$/, '');
const qs = JSON.parse(jsonStr);

const q79 = qs.find(q => q.id === 79);
console.log('Q79 in quiz/data/mln.js:');
console.log(JSON.stringify(q79, null, 2));
